package com.funcouple.app

/** {p} viene sostituito con il nome del partner; [custom] segna le carte scritte dalla coppia. */
data class Challenge(val text: String, val seconds: Int = 0, val custom: Boolean = false)

fun String.forPartner(partner: String) = replace("{p}", partner)

/** Verità per livello: Dolce, Piccante, Bollente, Estremo. */
val truths: List<List<Challenge>> = listOf(
    listOf(
        Challenge("Qual è stato il momento esatto in cui hai capito di desiderare {p}?"),
        Challenge("Quale parte del corpo di {p} ti fa impazzire di più?"),
        Challenge("Qual è il bacio più bello che vi siete mai dati? Raccontalo nei dettagli."),
        Challenge("Cosa indossa {p} quando ti sembra irresistibile?"),
        Challenge("Qual è il complimento più audace che non hai mai avuto il coraggio di fare a {p}?"),
        Challenge("Dove vorresti ricevere un bacio in questo preciso momento?"),
        Challenge("Qual è il ricordo più romantico che hai di voi due?"),
        Challenge("Quale canzone o profumo ti fa pensare a {p} in modo malizioso?"),
        Challenge("Qual è stata la prima cosa che hai pensato vedendo {p} senza vestiti?"),
        Challenge("Qual è il gesto di {p} che ti accende all'istante?"),
        Challenge("Com'è stato il nostro primo appuntamento visto dai tuoi occhi? Cosa hai pensato tornando a casa?"),
        Challenge("Cosa ti manca di più di {p} quando siete lontani?"),
        Challenge("Qual è il soprannome più tenero che vorresti dare a {p}?"),
        Challenge("In quale momento della giornata desideri di più {p}?"),
        Challenge("Qual è la cosa più romantica che {p} abbia mai fatto per te?"),
        Challenge("Cosa hai notato per prima cosa di {p} la prima volta che vi siete visti?"),
        Challenge("Dove ti piacerebbe portare {p} per un weekend solo vostro?"),
        Challenge("Che sapore hanno i baci di {p}? Descrivili."),
        Challenge("Come ti piace di più farti abbracciare da {p}?"),
        Challenge("Quale abitudine di {p} trovi segretamente adorabile?"),
        Challenge("Qual è la foto di {p} che guardi più spesso?"),
        Challenge("Hai mai sognato {p}? Racconta il sogno più bello."),
        Challenge("Cosa fa {p} che ti fa sentire davvero al centro del suo desiderio?"),
        Challenge("Qual è il vostro momento insieme che vorresti rivivere identico?"),
        Challenge("Quale parte del tuo corpo ti piace che {p} accarezzi?"),
        Challenge("Quale regalo faresti a {p} se non ci fossero limiti?"),
        Challenge("Qual è la cosa che {p} dice e che ti fa sciogliere?"),
        Challenge("Preferisci i baci lenti o quelli travolgenti? Perché?"),
        Challenge("Qual è il dettaglio del viso di {p} che potresti guardare per ore?"),
        Challenge("Cosa hai pensato la prima volta che avete dormito insieme?"),
    ),
    listOf(
        Challenge("Qual è la tua fantasia ricorrente su {p}?"),
        Challenge("Qual è il posto più insolito in cui vorresti fare l'amore?"),
        Challenge("Cosa ti piacerebbe che {p} ti facesse più spesso a letto?"),
        Challenge("Qual è stata la vostra notte più indimenticabile? Perché?"),
        Challenge("Preferisci comandare o lasciarti guidare? Spiega cosa ti piace."),
        Challenge("Qual è la cosa più audace che hai fatto pensando a {p}?"),
        Challenge("Quale capo di biancheria vorresti vedere addosso a {p}?"),
        Challenge("Qual è il messaggio più piccante che vorresti ricevere da {p}?"),
        Challenge("Luci accese o spente? E perché?"),
        Challenge("Qual è il tuo punto debole, quello che ti fa perdere il controllo?"),
        Challenge("Qual è stato il vostro bacio più eccitante? Dove eravate?"),
        Challenge("Ti è mai capitato di desiderare {p} in un momento del tutto inopportuno? Racconta."),
        Challenge("Qual è il posto di casa in cui non l'avete ancora fatto e in cui vorresti farlo?"),
        Challenge("Preferisci spogliare {p} o farti spogliare?"),
        Challenge("Qual è il preliminare a cui non rinunceresti mai?"),
        Challenge("Cosa pensi quando {p} esce dalla doccia?"),
        Challenge("Qual è la cosa che {p} fa senza saperlo e che ti eccita?"),
        Challenge("Mattina, pomeriggio o notte: quando ti piace di più fare l'amore?"),
        Challenge("Hai mai mandato, o voluto mandare, una foto provocante a {p}? Com'era?"),
        Challenge("Qual è il vestito che vorresti strappare di dosso a {p}?"),
        Challenge("Dove ti piace di più sentire le labbra di {p}?"),
        Challenge("Veloce e travolgente oppure lento e interminabile: cosa preferisci stasera?"),
        Challenge("Qual è stata la volta in cui hai fatto più fatica a tenere le mani lontane da {p}?"),
        Challenge("C'è una scena di un film che vorresti ricreare con {p}?"),
        Challenge("Cosa vorresti che {p} ti sussurrasse all'orecchio in questo momento?"),
        Challenge("Qual è la parte del tuo corpo più sensibile ai baci?"),
        Challenge("Hai mai pensato a {p} durante una riunione, una lezione o una cena? A cosa, di preciso?"),
        Challenge("Musica, silenzio o parole: cosa vuoi sentire mentre fate l'amore?"),
        Challenge("Qual è la cosa più audace che faresti con {p} in vacanza?"),
        Challenge("Cosa ti piace di più guardare di {p} mentre si spoglia?"),
    ),
    listOf(
        Challenge("Descrivi nei dettagli cosa vorresti fare a {p} in questo preciso momento."),
        Challenge("Qual è la fantasia che non hai mai osato confessare a {p}?"),
        Challenge("Qual è la posizione che ti fa godere di più, e perché?"),
        Challenge("Hai mai pensato a {p} mentre ti toccavi? Racconta."),
        Challenge("Cosa ti eccita di più: guardare, ascoltare o sentire le sue mani addosso?"),
        Challenge("Qual è la cosa più spinta che vorresti provare insieme almeno una volta?"),
        Challenge("Qual è il risveglio più eccitante che {p} potrebbe regalarti?"),
        Challenge("Qual è la frase che ti eccita di più se sussurrata da {p}?"),
        Challenge("Giocattoli, bende, manette: cosa ti incuriosisce di più?"),
        Challenge("Racconta l'orgasmo più intenso che hai avuto con {p}."),
        Challenge("Qual è il punto esatto in cui vuoi sentire la bocca di {p} adesso?"),
        Challenge("Descrivi a {p}, passo per passo, come ti piace ricevere le sue carezze più intime."),
        Challenge("Qual è il posto più rischioso in cui l'avete fatto, o in cui vorresti farlo?"),
        Challenge("Cosa ti porta all'orgasmo più in fretta di qualsiasi altra cosa?"),
        Challenge("Preferisci dare o ricevere piacere con la bocca? Perché?"),
        Challenge("Qual è il suono che fa {p} a letto e che ti eccita di più?"),
        Challenge("C'è qualcosa che {p} ti ha fatto una volta sola e che vorresti rifacesse?"),
        Challenge("Qual è la cosa più spinta che hai sognato di fare con {p}?"),
        Challenge("Ti piace quando {p} ti parla in modo esplicito? Cosa vorresti sentirti dire?"),
        Challenge("Qual è la posizione che non avete mai provato e che ti incuriosisce di più?"),
        Challenge("Dove ti piacerebbe che {p} venisse a svegliarti con la bocca?"),
        Challenge("Quando hai desiderato {p} così tanto da non riuscire a pensare ad altro?"),
        Challenge("Specchio sì o specchio no? Ti piacerebbe guardarvi mentre lo fate?"),
        Challenge("Qual è il tuo modo preferito di far perdere il controllo a {p}?"),
        Challenge("C'è un giocattolo che vorresti usare insieme a {p}? Quale?"),
        Challenge("Qual è stata la volta in cui avete fatto più rumore? Ti è piaciuto?"),
        Challenge("Cosa vorresti che {p} facesse con le mani mentre ti bacia?"),
        Challenge("Quanto vorresti che durassero i preliminari stanotte? E cosa ci metteresti dentro?"),
        Challenge("Qual è la cosa che ti eccita di più del corpo nudo di {p}?"),
        Challenge("Cosa ti passa per la testa nell'istante prima dell'orgasmo?"),
    ),
    listOf(
        Challenge("Qual è la fantasia più proibita che vorresti realizzare con {p}?"),
        Challenge("C'è qualcosa che vorresti che {p} ti ordinasse di fare?"),
        Challenge("Cosa vorresti che {p} ti facesse se avessi le mani legate?"),
        Challenge("Qual è il limite che ti piacerebbe superare insieme, stanotte?"),
        Challenge("Descrivi, senza censure, la notte perfetta con {p} dall'inizio alla fine."),
        Challenge("Ti ecciterebbe che {p} ti guardasse mentre ti dai piacere? Perché?"),
        Challenge("Qual è la cosa più sporca che vorresti sentirti dire da {p}?"),
        Challenge("Dove vorresti farlo con il rischio di essere scoperti?"),
        Challenge("Qual è il gioco di ruolo che vorresti provare con {p}?"),
        Challenge("Dominare o sottomettersi: fino a che punto ti spingeresti?"),
        Challenge("Qual è la cosa che non hai mai avuto il coraggio di chiedere a {p} a letto?"),
        Challenge("Occhi bendati e in balia di {p}: cosa speri che ti faccia?"),
        Challenge("C'è un ordine che vorresti dare a {p} e che non hai mai osato pronunciare?"),
        Challenge("Qual è la tua fantasia più sporca in assoluto? Raccontala senza saltare i dettagli."),
        Challenge("Ti ecciterebbe filmarvi mentre lo fate, solo per riguardarvi insieme? Perché?"),
        Challenge("Fin dove ti piacerebbe spingerti con sculacciate, morsi o graffi?"),
        Challenge("Qual è il posto pubblico in cui hai fantasticato di farlo con {p}?"),
        Challenge("Se {p} ti legasse al letto, qual è la prima cosa che vorresti ti facesse?"),
        Challenge("Qual è la cosa più estrema che faresti per {p} se te lo chiedesse stanotte?"),
        Challenge("Ti piacerebbe che {p} ti negasse il piacere fino a farti implorare?"),
        Challenge("C'è un travestimento o un ruolo che ti eccita e che non hai mai confessato?"),
        Challenge("Quale parte del tuo corpo vorresti che {p} esplorasse di più, e che finora ha trascurato?"),
        Challenge("Preferiresti una notte in cui decidi tutto tu o una in cui non decidi niente?"),
        Challenge("Qual è la frase più volgare che ti piacerebbe dire a {p} nel momento più intenso?"),
        Challenge("Qual è la fantasia che ti ha fatto arrossire anche solo a pensarla?"),
        Challenge("Quanto ti eccita l'idea di farlo dove qualcuno potrebbe sentirvi?"),
        Challenge("Se stanotte non ci fossero regole, quale sarebbe la prima che infrangeresti con {p}?"),
        Challenge("Cosa vorresti che {p} ti facesse mentre tieni le mani dietro la schiena?"),
        Challenge("Qual è il gioco di potere che ti tenta di più: comandare, obbedire o resistere?"),
        Challenge("Descrivi a {p} come vorresti finire questa serata, senza censurare niente."),
    ),
)

/** Obblighi per livello: Dolce, Piccante, Bollente, Estremo. */
val dares: List<List<Challenge>> = listOf(
    listOf(
        Challenge("Bacia {p} sul collo, lentamente, per 20 secondi.", 20),
        Challenge("Sussurra all'orecchio di {p} tre cose che adori del suo corpo."),
        Challenge("Fai a {p} un massaggio alle spalle per un minuto.", 60),
        Challenge("Guardatevi negli occhi in silenzio per 30 secondi, senza ridere.", 30),
        Challenge("Dai a {p} il bacio più lento di cui sei capace.", 30),
        Challenge("Accarezza il viso e i capelli di {p} tenendo gli occhi chiusi.", 30),
        Challenge("Balla un lento stretto a {p} per un minuto.", 60),
        Challenge("Disegna un cuore con la punta delle dita sulla schiena di {p}, sotto la maglietta."),
        Challenge("Bacia tre punti a tua scelta del corpo di {p}, sopra i vestiti."),
        Challenge("Togli un indumento a {p}, molto lentamente."),
        Challenge("Bacia la fronte, il naso e poi le labbra di {p}, lentissimamente."),
        Challenge("Bacia una per una le dita di {p}."),
        Challenge("Abbraccia {p} da dietro e resta così per 30 secondi.", 30),
        Challenge("Guarda {p} negli occhi e racconta il momento in cui hai capito che era amore."),
        Challenge("Fai a {p} un massaggio alle mani per un minuto.", 60),
        Challenge("Sfiora le labbra di {p} con le tue, senza baciarle, per 20 secondi.", 20),
        Challenge("Imbocca {p} con qualcosa di buono, tenendo gli occhi chiusi."),
        Challenge("Accarezza la nuca di {p} con la punta delle dita per 30 secondi.", 30),
        Challenge("Scrivi una parola con il dito sulla schiena di {p}: deve indovinarla."),
        Challenge("Dai a {p} cinque baci in cinque punti diversi del viso."),
        Challenge("Appoggia la testa sulle gambe di {p} e fatti accarezzare i capelli per un minuto.", 60),
        Challenge("Sussurra a {p} il tuo ricordo più bello di voi due."),
        Challenge("Massaggia i piedi di {p} per un minuto.", 60),
        Challenge("Bacia il polso di {p} e risali lentamente fino al gomito."),
        Challenge("Appoggia l'orecchio sul petto di {p} e ascolta il suo cuore per 20 secondi.", 20),
        Challenge("Fai un complimento a {p} per ogni dito di una mano."),
        Challenge("Baciatevi tenendovi il viso tra le mani per 30 secondi.", 30),
        Challenge("Strofina il naso contro quello di {p}, poi ruba un bacio."),
        Challenge("Stringi forte {p} e dondolate insieme, a occhi chiusi, per 30 secondi.", 30),
        Challenge("Bacia la spalla di {p}, scostando appena il vestito."),
    ),
    listOf(
        Challenge("Togliti un indumento scelto da {p}."),
        Challenge("Bacia {p} dall'orecchio fino alla clavicola, senza usare le mani.", 30),
        Challenge("Massaggia l'interno coscia di {p} per un minuto, senza andare oltre.", 60),
        Challenge("Mordicchia delicatamente il labbro inferiore di {p}."),
        Challenge("Fai chiudere gli occhi a {p} e bacia tre punti a sorpresa del suo corpo."),
        Challenge("Siediti a cavalcioni su {p} e baciatevi per un minuto.", 60),
        Challenge("Sussurra a {p}, nei dettagli, cosa hai intenzione di fare stanotte con il suo corpo."),
        Challenge("Passa un cubetto di ghiaccio (o le dita fredde) lungo la schiena di {p}."),
        Challenge("Fai uno spogliarello di 60 secondi per {p}.", 60),
        Challenge("Lecca lentamente il collo di {p} e poi soffiaci sopra."),
        Challenge("Slaccia un bottone o una cerniera di {p} usando solo i denti."),
        Challenge("Fai sedere {p} e balla in modo provocante davanti ai suoi occhi per un minuto.", 60),
        Challenge("Infila una mano sotto la maglietta di {p} e accarezza la sua schiena per 30 secondi.", 30),
        Challenge("Bacia la pancia di {p}, tutto intorno all'ombelico."),
        Challenge("Sussurra a {p} tre cose che vuoi fare stanotte, sfiorando il suo orecchio con le labbra."),
        Challenge("Fatti togliere un indumento da {p}, che può usare solo la bocca."),
        Challenge("Bacia {p} con passione contro il muro per 30 secondi.", 30),
        Challenge("Passa la lingua lungo la clavicola di {p}."),
        Challenge("Accarezza le cosce di {p} dal ginocchio in su, fermandoti all'ultimo momento.", 30),
        Challenge("Lascia a {p} un succhiotto leggero, dove non si vede."),
        Challenge("Chiudi gli occhi: {p} ti fa toccare una parte del suo corpo e devi indovinare quale."),
        Challenge("Mordicchia il lobo dell'orecchio di {p} e sussurra il suo nome."),
        Challenge("Sdraiati sopra {p} e baciatevi per un minuto senza usare le mani.", 60),
        Challenge("Massaggia il fondoschiena di {p} per un minuto.", 60),
        Challenge("Mangia qualcosa di dolce direttamente dalle labbra di {p}."),
        Challenge("Togliti l'intimo senza togliere il resto e consegnalo a {p}."),
        Challenge("Disegna con la lingua una lettera sul collo di {p}: deve indovinarla."),
        Challenge("Guida la mano di {p} sul tuo corpo, dove vuoi sentirla, per 30 secondi.", 30),
        Challenge("Bacia l'interno del polso, del gomito e del ginocchio di {p}."),
        Challenge("Resta a un centimetro dalle labbra di {p} per 30 secondi: chi bacia per primo perde.", 30),
    ),
    listOf(
        Challenge("Spoglia {p} usando solo la bocca, per quanto riesci.", 90),
        Challenge("Bacia e lecca l'interno coscia di {p} per un minuto, avvicinandoti senza mai arrivare.", 60),
        Challenge("Fatti guidare: {p} prende la tua mano e ti mostra dove e come desidera le tue carezze.", 60),
        Challenge("Massaggia {p} con olio o crema su tutto il corpo per due minuti.", 120),
        Challenge("Resta in intimo e fai una lap dance a {p}: può guardare ma non toccare.", 90),
        Challenge("Usa solo la lingua per tracciare un percorso dal collo all'ombelico di {p}."),
        Challenge("Tieni ferme le mani di {p} sopra la testa e bacia il suo corpo dove vuoi.", 60),
        Challenge("Stuzzica {p} con la bocca dove preferisce, ma fermati dopo 45 secondi.", 45),
        Challenge("Sussurra a {p} la tua fantasia più sporca mentre le tue mani esplorano il suo corpo."),
        Challenge("Scegli una posizione dal Kamasutra e provatela, ancora vestiti, per 30 secondi.", 30),
        Challenge("Bacia il petto di {p}, soffermandoti dove reagisce di più.", 60),
        Challenge("Fai sdraiare {p} e percorri tutto il suo corpo con le labbra, dalla caviglia al collo.", 90),
        Challenge("Accarezza {p} sopra l'intimo per un minuto, senza mai infilare la mano.", 60),
        Challenge("Versa qualche goccia di qualcosa di dolce sul corpo di {p} e leccala via."),
        Challenge("Mettiti a cavalcioni su {p} e muoviti lentamente per un minuto, con l'intimo ancora addosso.", 60),
        Challenge("Togli l'intimo a {p} usando i denti."),
        Challenge("Massaggia con l'olio l'interno coscia di {p}, salendo sempre di più.", 90),
        Challenge("Fai chiudere gli occhi a {p} e alterna baci, morsi leggeri e soffi dove non se lo aspetta.", 60),
        Challenge("Mostra a {p} come ti tocchi quando nessuno ti guarda, per 30 secondi.", 30),
        Challenge("Bacia il fondoschiena di {p} e mordicchia piano."),
        Challenge("Sussurra a {p} cosa stai per fare, poi fallo. Per tre volte di fila."),
        Challenge("Tieni {p} contro il muro con le mani bloccate e bacia il suo collo per un minuto.", 60),
        Challenge("Passa un cubetto di ghiaccio sui capezzoli di {p}, poi scaldali con la bocca."),
        Challenge("Stuzzica {p} con la punta della lingua, nel punto che sceglie, per 45 secondi.", 45),
        Challenge("Spogliatevi a vicenda completamente, un indumento alla volta e senza fretta."),
        Challenge("Accarezza {p} dove preferisce guardandovi negli occhi: vietato distogliere lo sguardo.", 60),
        Challenge("Fatti bendare da {p} e lascia che usi le tue mani per accarezzarsi.", 60),
        Challenge("Bacia la schiena di {p} dalla nuca fino in fondo, molto lentamente.", 60),
        Challenge("Strusciati contro {p} da dietro, baciando il suo collo, per un minuto.", 60),
        Challenge("Chiedi a {p} qual è il suo punto più sensibile e dedicagli un minuto di sola bocca.", 60),
    ),
    listOf(
        Challenge("Per i prossimi 3 minuti {p} comanda e tu esaudisci ogni suo desiderio.", 180),
        Challenge("Benda {p} e stuzzica il suo corpo con bocca e mani per due minuti: non può toccarti.", 120),
        Challenge("Lega delicatamente i polsi di {p} con una sciarpa e fai ciò che vuoi per due minuti.", 120),
        Challenge("Porta {p} al limite con la bocca e fermati un attimo prima. Poi sorridi."),
        Challenge("Datti piacere davanti a {p} per un minuto: può solo guardare.", 60),
        Challenge("Scegli una posizione del Kamasutra che non avete mai provato: si fa adesso."),
        Challenge("Dedica due minuti di piacere orale a {p}: il ritmo lo decide {p}.", 120),
        Challenge("Completamente nudi: 60 secondi di baci ovunque, vietato usare le mani.", 60),
        Challenge("Fate l'amore per un minuto esatto nella posizione scelta da {p}, poi fermatevi e continuate a giocare.", 60),
        Challenge("Sussurra a {p} un ordine: deve eseguirlo subito."),
        Challenge("Fatti legare i polsi da {p}: per due minuti può fare di te ciò che vuole.", 120),
        Challenge("Porta {p} vicino all'orgasmo con le mani per tre volte, fermandoti ogni volta."),
        Challenge("Mettiti in ginocchio davanti a {p} e usa la bocca finché non ti dice basta."),
        Challenge("{p} sceglie una posizione: la tenete per due minuti esatti, poi vi fermate.", 120),
        Challenge("Dai a {p} tre sculacciate: l'intensità la decide {p}."),
        Challenge("Bendatevi tutti e due ed esploratevi solo con mani e bocca per due minuti.", 120),
        Challenge("Fate l'amore davanti a uno specchio per un minuto, senza smettere di guardarvi.", 60),
        Challenge("Ordina a {p} di toccarsi esattamente come dici tu, per un minuto.", 60),
        Challenge("Sdraiati: {p} si mette a cavalcioni sul tuo viso per un minuto.", 60),
        Challenge("Usa un giocattolo, o le dita, su {p} mentre tieni fermi i suoi polsi.", 90),
        Challenge("Per tre minuti puoi dire solo sì a tutto ciò che {p} ti chiede.", 180),
        Challenge("Fate un 69 per due minuti: chi si ferma per primo paga pegno.", 120),
        Challenge("Stuzzica {p} con la bocca per due minuti senza concedere l'orgasmo: deve chiedertelo per favore.", 120),
        Challenge("Prendi {p} per i capelli, con delicatezza, e guida la sua bocca dove vuoi tu."),
        Challenge("Nudi, sotto la doccia o sul pavimento: tu scegli dove, {p} sceglie come."),
        Challenge("Lascia che {p} scriva il suo nome sul tuo corpo con la lingua, dove vuole."),
        Challenge("Fatelo per un minuto senza emettere un suono: chi geme per primo perde.", 60),
        Challenge("Usa solo la bocca per portare {p} fino in fondo: stavolta non ci si ferma."),
        Challenge("Descrivi ad alta voce, mentre lo fai, tutto ciò che stai facendo al corpo di {p}.", 90),
        Challenge("Chiudi gli occhi: {p} ti guida in una posizione a sorpresa e si comincia subito."),
    ),
)

data class DiceAction(val icon: FcIcon, val verb: String)

// Ogni dado ha sei facce: l'indice nella lista è la faccia del cubo.
val diceActions = listOf(
    DiceAction(FcIcon.LIPS, "Bacia"),
    DiceAction(FcIcon.TONGUE, "Lecca"),
    DiceAction(FcIcon.FANGS, "Mordicchia"),
    DiceAction(FcIcon.FEATHER, "Accarezza"),
    DiceAction(FcIcon.HAND, "Massaggia"),
    DiceAction(FcIcon.DROP, "Succhia"),
)

/** [label] è il testo sulla faccia del dado, [phrase] quello usato nella frase finale. */
data class DicePart(val label: String, val phrase: String)

val diceParts = listOf(
    DicePart("Collo", "il collo"),
    DicePart("Labbra", "le labbra"),
    DicePart("Petto", "il petto"),
    DicePart("Interno coscia", "l'interno coscia"),
    DicePart("Schiena", "la schiena"),
    DicePart("Fondoschiena", "il fondoschiena"),
)

val diceDurations = listOf(15, 20, 30, 45, 60, 90)

data class WheelPrize(
    val icon: FcIcon,
    val label: String,
    val text: String,
    val seconds: Int = 0,
    val randomPosition: Boolean = false,
)

val wheelPrizes = listOf(
    WheelPrize(FcIcon.HAND, "Massaggio", "{p} ti regala 5 minuti di massaggio con olio, dove vuoi tu.", 300),
    WheelPrize(FcIcon.LIPS, "Dieci baci", "Dieci baci in dieci punti diversi del tuo corpo: li scegli tu, li dà {p}."),
    WheelPrize(FcIcon.HANGER, "Strip", "Fai uno spogliarello per {p} sulla vostra canzone preferita."),
    WheelPrize(FcIcon.BLINDFOLD, "Bendati", "{p} ti benda e ti bacia dove vuole per 2 minuti.", 120),
    WheelPrize(FcIcon.CHAT, "Fantasia", "Sussurra all'orecchio di {p} una fantasia che non hai mai confessato."),
    WheelPrize(FcIcon.CROWN, "Comando io", "Per 3 minuti comandi tu: {p} esaudisce ogni tuo desiderio.", 180),
    WheelPrize(FcIcon.MOON, "Posizione", "Il destino sceglie per voi una posizione del Kamasutra.", randomPosition = true),
    WheelPrize(FcIcon.FEATHER, "Brividi", "Sfiora tutto il corpo di {p} con la punta delle dita, senza fermarti mai.", 120),
    WheelPrize(FcIcon.SNOWFLAKE, "Ghiaccio", "Passa un cubetto di ghiaccio sul corpo di {p}, seguendolo con la bocca.", 60),
    WheelPrize(FcIcon.TONGUE, "Assaggio", "Metti qualcosa di dolce su un punto del tuo corpo: {p} lo assaggia."),
    WheelPrize(FcIcon.SHOWER, "Doccia", "Doccia insieme: insaponatevi a vicenda, molto lentamente."),
    WheelPrize(FcIcon.JOKER, "Jolly", "Jolly! Chiedi a {p} qualunque cosa: non può rifiutare."),
)

/** Penitenze per chi passa a Verità o Obbligo. */
val penalties = listOf(
    "Togliti un indumento: lo sceglie {p}.",
    "Un bacio lungo 20 secondi, nel punto che decide {p}.",
    "Fai a {p} un massaggio di un minuto, dove vuole.",
    "{p} ti dà una sculacciata. O due.",
    "Rispondi a una domanda a scelta di {p}, senza mentire.",
    "Fino al tuo prossimo turno tieni le mani dietro la schiena.",
    "Di' a {p} la cosa più audace che ti viene in mente, guardando i suoi occhi.",
    "{p} sceglie un punto del tuo corpo e lo bacia: tu non puoi muoverti.",
    "Fai sentire a {p} il tuo verso di piacere più convincente.",
    "Dieci secondi di ballo sexy per {p}. Subito.",
    "Lascia che {p} ti tolga un indumento usando i denti.",
    "Sussurra a {p} perché hai passato: la vera ragione.",
)

/** Quarto dado: il modo in cui eseguire la sfida. */
data class DiceMode(val icon: FcIcon, val label: String, val phrase: String)

val diceModes = listOf(
    DiceMode(FcIcon.BLINDFOLD, "Bendati", "a occhi bendati"),
    DiceMode(FcIcon.WAVES, "Lentissimo", "il più lentamente possibile"),
    DiceMode(FcIcon.SNOWFLAKE, "Col ghiaccio", "dopo aver tenuto un cubetto di ghiaccio in bocca"),
    DiceMode(FcIcon.CHAT, "Sussurrando", "sussurrando quello che provi"),
    DiceMode(FcIcon.MOON, "Al buio", "a luci spente"),
    DiceMode(FcIcon.FLAME, "Con passione", "con tutta la passione che hai"),
)

data class Coupon(val id: String, val title: String, val text: String, val cost: Int, val icon: FcIcon)

val coupons = listOf(
    Coupon("baci", "Cento baci", "Cento baci, tutti dove decido io.", 2, FcIcon.LIPS),
    Coupon("massaggio", "Massaggio lungo", "Dieci minuti di massaggio con olio, senza fretta.", 3, FcIcon.HAND),
    Coupon("colazione", "Risveglio dolce", "Colazione a letto. Il resto viene da sé.", 3, FcIcon.FLOWER),
    Coupon("doccia", "Doccia a due", "Una doccia insieme, nel momento che scelgo io.", 4, FcIcon.SHOWER),
    Coupon("strip", "Spogliarello privato", "Uno spogliarello tutto per me, con la musica che voglio.", 5, FcIcon.HANGER),
    Coupon("posizione", "Scelgo io", "Stanotte la posizione la decido io.", 5, FcIcon.MOON),
    Coupon("comando", "Comando io", "Per quindici minuti si fa tutto quello che dico.", 6, FcIcon.CROWN),
    Coupon("sveglia", "Sorpresa piccante", "Un risveglio a sorpresa, il più piccante possibile.", 8, FcIcon.SPARKLE),
    Coupon("serata", "Serata per me", "Una serata intera dedicata solo al mio piacere.", 10, FcIcon.FLAME),
    Coupon("desiderio", "Desiderio libero", "Un desiderio a mia scelta: si può dire solo sì.", 12, FcIcon.STAR),
)

/** Frasi di "Non ho mai" per livello: Dolce, Piccante, Bollente, Estremo. */
val neverStatements: List<List<String>> = listOf(
    listOf(
        "Non ho mai finto di dormire per ricevere una coccola.",
        "Non ho mai mandato un messaggio d'amore alla persona sbagliata.",
        "Non ho mai baciato qualcuno al primo appuntamento.",
        "Non ho mai avuto una cotta per un insegnante o un capo.",
        "Non ho mai scritto una lettera d'amore.",
        "Non ho mai sbirciato di nascosto il telefono del partner.",
        "Non ho mai ballato un lento in cucina.",
        "Non ho mai immaginato il nostro primo bacio prima che succedesse.",
        "Non ho mai organizzato una sorpresa romantica finita male.",
        "Non ho mai pianto per un film d'amore.",
        "Non ho mai dato un bacio sotto la pioggia.",
        "Non ho mai detto ti amo prima che lo dicesse l'altra persona.",
        "Non ho mai conservato un ricordo di una vecchia fiamma.",
        "Non ho mai fatto un bagno a lume di candela in due.",
        "Non ho mai passato una notte intera in un abbraccio.",
    ),
    listOf(
        "Non ho mai fatto il bagno senza costume.",
        "Non ho mai mandato una foto provocante.",
        "Non ho mai fatto sexting.",
        "Non ho mai baciato qualcuno di cui non sapevo il nome.",
        "Non ho mai indossato biancheria sexy per fare una sorpresa.",
        "Non ho mai fatto uno spogliarello.",
        "Non ho mai fatto un sogno erotico su una persona che conosco.",
        "Non ho mai flirtato per ottenere qualcosa.",
        "Non ho mai fatto la doccia in due.",
        "Non ho mai pomiciato al cinema.",
        "Non ho mai dormito senza niente addosso.",
        "Non ho mai avuto un succhiotto difficile da nascondere.",
        "Non ho mai giocato a un gioco in cui ci si spoglia.",
        "Non ho mai letto o guardato qualcosa di erotico insieme al partner.",
        "Non ho mai fatto un massaggio finito in tutt'altro modo.",
    ),
    listOf(
        "Non ho mai fatto l'amore in macchina.",
        "Non ho mai fatto l'amore all'aperto.",
        "Non ho mai usato un giocattolo erotico.",
        "Non ho mai fatto l'amore di nascosto in una casa non mia.",
        "Non ho mai fatto l'amore più di tre volte in una notte.",
        "Non ho mai finto un orgasmo.",
        "Non ho mai fatto l'amore in acqua.",
        "Non ho mai fatto l'amore davanti a uno specchio.",
        "Non ho mai usato del cibo durante il sesso.",
        "Non ho mai fatto sesso al telefono o in videochiamata.",
        "Non ho mai fatto l'amore sul posto di lavoro.",
        "Non ho mai rischiato di farmi scoprire sul più bello.",
        "Non ho mai svegliato qualcuno nel modo più piccante possibile.",
        "Non ho mai fatto l'amore con tutte le luci accese.",
        "Non ho mai avuto un orgasmo così forte da restare senza parole.",
    ),
    listOf(
        "Non ho mai usato una benda o delle manette.",
        "Non ho mai fatto l'amore in un luogo pubblico.",
        "Non ho mai filmato o fotografato un momento intimo.",
        "Non ho mai provato un gioco di dominazione.",
        "Non ho mai dato o ricevuto una sculacciata a letto.",
        "Non ho mai avuto una fantasia che non ho il coraggio di dire.",
        "Non ho mai fatto l'amore in un camerino o in un bagno pubblico.",
        "Non ho mai provato il sesso anale.",
        "Non ho mai fatto l'amore con qualcuno nella stanza accanto.",
        "Non ho mai detto parole davvero sporche a letto.",
        "Non ho mai implorato per avere un orgasmo.",
        "Non ho mai fatto l'amore in aereo, in treno o in barca.",
        "Non ho mai comprato qualcosa in un sexy shop.",
        "Non ho mai avuto una fantasia con più di due persone.",
        "Non ho mai portato qualcuno al limite per poi fermarmi apposta.",
    ),
)
