package com.funcouple.app

// FILE GENERATO da tools/gen_positions.py: modifica lo script, non questo file.

/**
 * [image] è l'illustrazione della posizione: A è la figura rosa, B quella viola.
 * Le posizioni senza scheda hanno solo nome e illustrazione: testi vuoti e valutazioni a zero.
 */
data class Position(
    val id: String,
    val name: String,
    val image: Int,
    val tagline: String = "",
    val difficulty: Int = 0,
    val intimacy: Int = 0,
    val intensity: Int = 0,
    val description: String = "",
    val tip: String = "",
)

val difficultyNames = listOf("", "Facile", "Media", "Difficile")

val positions = listOf(
    Position(
        id = "missionario",
        name = "Il Missionario",
        image = R.drawable.pos_missionario,
        tagline = "Il grande classico, occhi negli occhi",
        difficulty = 1,
        intimacy = 5,
        intensity = 2,
        description = "A si sdraia sulla schiena con le ginocchia piegate. B si distende sopra, sostenendosi sugli avambracci, petto contro petto. Il contatto visivo e i baci fanno tutto il resto.",
        tip = "Un cuscino sotto il bacino di A cambia l'angolo e rende tutto molto più intenso.",
    ),
    Position(
        id = "amazzone",
        name = "L'Amazzone",
        image = R.drawable.pos_amazzone,
        tagline = "Chi sta sopra detta il ritmo",
        difficulty = 1,
        intimacy = 4,
        intensity = 4,
        description = "B è sdraiato sulla schiena. A si mette a cavalcioni sul suo bacino, in ginocchio e con il busto eretto, le mani appoggiate sul petto di B, e controlla profondità e velocità.",
        tip = "Alternate movimenti circolari lenti a spinte più decise: l'attesa è metà del piacere.",
    ),
    Position(
        id = "cucchiaio",
        name = "Il Cucchiaio",
        image = R.drawable.pos_cucchiaio,
        tagline = "Lento, pigro e dolcissimo",
        difficulty = 1,
        intimacy = 5,
        intensity = 2,
        description = "Entrambi sdraiati sul fianco, rivolti nella stessa direzione. B abbraccia A da dietro, i corpi aderiscono dalla testa ai piedi e i movimenti sono lenti e profondi.",
        tip = "Perfetta al risveglio. La mano libera di B può esplorare tutto il corpo di A.",
    ),
    Position(
        id = "pecorina",
        name = "La Pecorina",
        image = R.drawable.pos_pecorina,
        tagline = "Istinto puro",
        difficulty = 1,
        intimacy = 2,
        intensity = 5,
        description = "A si mette a quattro zampe, con la schiena leggermente inarcata. B si inginocchia dietro, le afferra i fianchi e guida il movimento.",
        tip = "Se A appoggia petto e avambracci sul letto, l'angolo diventa ancora più profondo.",
    ),
    Position(
        id = "loto",
        name = "Il Loto",
        image = R.drawable.pos_loto,
        tagline = "Abbraccio totale, respiro all'unisono",
        difficulty = 2,
        intimacy = 5,
        intensity = 3,
        description = "B si siede a gambe incrociate. A si siede sul suo grembo, di fronte, avvolgendo gambe e braccia intorno al suo corpo. Ci si muove dondolando insieme.",
        tip = "Sincronizzate il respiro e guardatevi negli occhi: è la posizione tantrica per eccellenza.",
    ),
    Position(
        id = "amazzone_rovesciata",
        name = "L'Amazzone Rovesciata",
        image = R.drawable.pos_amazzone_rovesciata,
        tagline = "Uno spettacolo da non perdere",
        difficulty = 2,
        intimacy = 2,
        intensity = 5,
        description = "B è sdraiato sulla schiena. A si mette a cavalcioni dandogli le spalle, appoggia le mani sulle sue cosce e si muove avanti e indietro.",
        tip = "B può sollevare leggermente le ginocchia per offrire ad A un appoggio in più.",
    ),
    Position(
        id = "incudine",
        name = "L'Incudine",
        image = R.drawable.pos_incudine,
        tagline = "Profonda e travolgente",
        difficulty = 2,
        intimacy = 3,
        intensity = 5,
        description = "A è sdraiata sulla schiena e solleva le gambe fino ad appoggiarle sulle spalle di B, che è in ginocchio e si piega in avanti sostenendosi sulle mani.",
        tip = "Andate per gradi: più B si piega in avanti, più la penetrazione è profonda.",
    ),
    Position(
        id = "trono",
        name = "Il Trono",
        image = R.drawable.pos_trono,
        tagline = "Seduti, vicinissimi",
        difficulty = 1,
        intimacy = 3,
        intensity = 3,
        description = "B si siede su una sedia robusta. A si siede sul suo grembo dandogli le spalle, con i piedi a terra, e si muove su e giù mentre B la stringe per la vita.",
        tip = "Le mani di B sono libere: è il momento ideale per carezze e baci sul collo.",
    ),
    Position(
        id = "abbraccio_sospeso",
        name = "L'Abbraccio Sospeso",
        image = R.drawable.pos_abbraccio_sospeso,
        tagline = "Passione senza gravità",
        difficulty = 3,
        intimacy = 4,
        intensity = 5,
        description = "B è in piedi e solleva A sorreggendola sotto le cosce. A avvolge le gambe intorno ai suoi fianchi e le braccia intorno al suo collo.",
        tip = "Appoggiate la schiena di A a una parete: meno fatica, più resistenza.",
    ),
    Position(
        id = "ponte",
        name = "Il Ponte",
        image = R.drawable.pos_ponte,
        tagline = "Per coppie acrobatiche",
        difficulty = 3,
        intimacy = 2,
        intensity = 4,
        description = "B si solleva a ponte, appoggiato su mani e piedi con il ventre verso l'alto. A si mette a cavalcioni in piedi sopra il suo bacino e si abbassa quanto basta.",
        tip = "Serve forza nelle braccia: provatela per poco tempo, o con un pouf sotto la schiena di B.",
    ),
    Position(
        id = "carriola",
        name = "La Carriola",
        image = R.drawable.pos_carriola,
        tagline = "Divertente quanto impegnativa",
        difficulty = 3,
        intimacy = 2,
        intensity = 4,
        description = "A appoggia le mani a terra mentre B, in piedi, la solleva per le cosce. A stringe le gambe intorno ai fianchi di B.",
        tip = "Più facile se A appoggia gli avambracci sul bordo del letto invece che a terra.",
    ),
    Position(
        id = "sessantanove",
        name = "Il 69",
        image = R.drawable.pos_sessantanove,
        tagline = "Dare e ricevere, insieme",
        difficulty = 2,
        intimacy = 4,
        intensity = 4,
        description = "B è sdraiato sulla schiena. A si posiziona sopra, in direzione opposta, con le ginocchia ai lati della sua testa: ognuno dedica la bocca al piacere dell'altro.",
        tip = "Provatela anche sdraiati sul fianco: più comoda e si resiste molto più a lungo.",
    ),
    Position(
        id = "sfinge",
        name = "La Sfinge",
        image = R.drawable.pos_sfinge,
        tagline = "Pelle contro pelle",
        difficulty = 1,
        intimacy = 4,
        intensity = 3,
        description = "A si sdraia a pancia in giù, sollevando appena il busto sugli avambracci. B si distende sopra la sua schiena, con le gambe all'esterno delle sue.",
        tip = "Un cuscino sotto il bacino di A e baci sulla nuca: brividi garantiti.",
    ),
    Position(
        id = "forbici",
        name = "Le Forbici",
        image = R.drawable.pos_forbici,
        tagline = "Intreccio perfetto",
        difficulty = 2,
        intimacy = 3,
        intensity = 3,
        description = "Sdraiati in direzioni opposte, i due partner intrecciano le gambe come lame di forbice fino a far aderire i bacini. Ci si muove ondeggiando lentamente.",
        tip = "Tenetevi per mano o per le caviglie per darvi il ritmo a vicenda.",
    ),
    Position(
        id = "farfalla",
        name = "La Farfalla",
        image = R.drawable.pos_farfalla,
        tagline = "Sul bordo del letto",
        difficulty = 2,
        intimacy = 3,
        intensity = 5,
        description = "A si sdraia sulla schiena con il bacino sul bordo del letto e appoggia le gambe sulle spalle di B, che resta in piedi e le sostiene i fianchi.",
        tip = "Regolate l'altezza con un cuscino: quando i bacini sono allineati è perfetta.",
    ),
    Position(
        id = "muro",
        name = "Contro il Muro",
        image = R.drawable.pos_muro,
        tagline = "Quando non si può aspettare",
        difficulty = 2,
        intimacy = 3,
        intensity = 5,
        description = "A è in piedi, leggermente piegata in avanti con le mani appoggiate alla parete. B si posiziona dietro, in piedi, e la stringe per i fianchi.",
        tip = "Se c'è differenza di altezza, A può salire su un gradino o divaricare un po' le gambe.",
    ),
    Position(
        id = "rana",
        name = "La Rana",
        image = R.drawable.pos_rana,
        tagline = "Accovacciata, padrona del gioco",
        difficulty = 2,
        intimacy = 3,
        intensity = 5,
        description = "B è sdraiato sulla schiena. A si accovaccia sopra di lui con i piedi ben piantati ai lati dei suoi fianchi e le mani sul suo petto, e molleggia su e giù.",
        tip = "È faticosa per le cosce: B può sostenere A sotto i glutei per aiutarla a tenere il ritmo.",
    ),
    Position(
        id = "abbraccio_amazzone",
        name = "L'Amazzone Distesa",
        image = R.drawable.pos_abbraccio_amazzone,
        tagline = "Sopra, ma cuore a cuore",
        difficulty = 1,
        intimacy = 5,
        intensity = 3,
        description = "B è sdraiato sulla schiena. A si distende su di lui, petto contro petto, con le ginocchia ai lati dei suoi fianchi, e si muove scivolando avanti e indietro.",
        tip = "Movimenti piccoli e lenti: qui conta lo sfregamento, non la profondità.",
    ),
    Position(
        id = "gatto",
        name = "Il Gatto",
        image = R.drawable.pos_gatto,
        tagline = "Schiena inarcata, fianchi in alto",
        difficulty = 1,
        intimacy = 2,
        intensity = 5,
        description = "A è in ginocchio con il petto e le braccia distesi sul letto e i fianchi sollevati. B si inginocchia dietro di lei e la tiene per i fianchi.",
        tip = "Un cuscino sotto il petto di A rende la posizione comoda anche a lungo.",
    ),
    Position(
        id = "inchino",
        name = "L'Inchino",
        image = R.drawable.pos_inchino,
        tagline = "In piedi, senza appoggi",
        difficulty = 2,
        intimacy = 2,
        intensity = 5,
        description = "A è in piedi e si piega in avanti fino a toccare le caviglie o il pavimento. B resta in piedi dietro di lei e la sostiene saldamente per i fianchi.",
        tip = "A può appoggiare le mani su uno sgabello basso: più equilibrio, meno tensione sulle gambe.",
    ),
    Position(
        id = "tavolo",
        name = "Il Tavolo",
        image = R.drawable.pos_tavolo,
        tagline = "La cucina non è solo per cucinare",
        difficulty = 2,
        intimacy = 4,
        intensity = 4,
        description = "A si siede sul bordo di un tavolo, appoggiandosi all'indietro su una mano. B resta in piedi di fronte a lei, che gli avvolge le gambe intorno ai fianchi.",
        tip = "L'altezza giusta è quella in cui i bacini sono allineati: provate anche con il piano della cucina.",
    ),
    Position(
        id = "scrivania",
        name = "La Scrivania",
        image = R.drawable.pos_scrivania,
        tagline = "Urgente e irresistibile",
        difficulty = 1,
        intimacy = 2,
        intensity = 5,
        description = "A si piega in avanti e distende il busto su un tavolo o una scrivania, con i piedi a terra. B resta in piedi dietro di lei.",
        tip = "Un asciugamano piegato sul bordo evita che lo spigolo dia fastidio.",
    ),
    Position(
        id = "dondolo",
        name = "Il Dondolo",
        image = R.drawable.pos_dondolo,
        tagline = "Faccia a faccia sulla sedia",
        difficulty = 1,
        intimacy = 5,
        intensity = 3,
        description = "B si siede su una sedia senza braccioli. A si siede a cavalcioni su di lui, guardandolo, con le braccia intorno al suo collo, e dondola avanti e indietro.",
        tip = "Se A arriva con i piedi a terra può darsi la spinta e controllare tutto il movimento.",
    ),
    Position(
        id = "sdraio",
        name = "La Sdraio",
        image = R.drawable.pos_sdraio,
        tagline = "Rilassati, ma non troppo",
        difficulty = 2,
        intimacy = 2,
        intensity = 4,
        description = "B si siede a terra con le gambe distese e il busto inclinato all'indietro, appoggiato sulle mani. A si siede sul suo grembo dandogli le spalle, con i piedi a terra.",
        tip = "A può appoggiare le mani sulle ginocchia di B per spingersi e variare l'angolo.",
    ),
    Position(
        id = "poltrona",
        name = "La Poltrona",
        image = R.drawable.pos_poltrona,
        tagline = "Il divano come alleato",
        difficulty = 2,
        intimacy = 2,
        intensity = 5,
        description = "A si inginocchia sul divano o su una poltrona, aggrappandosi allo schienale. B resta in piedi dietro di lei.",
        tip = "Lo schienale dà ad A un appoggio perfetto per spingere all'indietro e dettare il ritmo.",
    ),
    Position(
        id = "candela",
        name = "La Candela",
        image = R.drawable.pos_candela,
        tagline = "Sottosopra",
        difficulty = 3,
        intimacy = 2,
        intensity = 4,
        description = "A si sdraia e solleva gambe e bacino verso l'alto, in appoggio sulle spalle, sostenendosi la schiena con le mani. B si inginocchia davanti a lei e la sorregge per le gambe.",
        tip = "Tenetela per poco: è una posizione da provare per gioco, non una maratona.",
    ),
    Position(
        id = "scivolata",
        name = "La Scivolata",
        image = R.drawable.pos_scivolata,
        tagline = "Stretti dalla testa ai piedi",
        difficulty = 1,
        intimacy = 5,
        intensity = 3,
        description = "A è sdraiata sulla schiena con le gambe distese e unite. B si distende sopra di lei, con le gambe all'esterno delle sue, e si muove scivolando verso l'alto e verso il basso.",
        tip = "Tenere le gambe strette aumenta l'attrito e lo sfregamento: sensazioni molto intense per entrambi.",
    ),
    Position(
        id = "ballerino",
        name = "Il Passo di Danza",
        image = R.drawable.pos_ballerino,
        tagline = "In piedi, uno contro l'altra",
        difficulty = 2,
        intimacy = 4,
        intensity = 4,
        description = "In piedi, faccia a faccia. A solleva una gamba e la avvolge intorno al fianco di B, che la sostiene sotto la coscia mentre lei gli si aggrappa al collo.",
        tip = "Con la schiena di A contro una parete diventa molto più stabile.",
    ),
    Position(
        id = "spaccata",
        name = "La Spaccata",
        image = R.drawable.pos_spaccata,
        tagline = "Una gamba su, una giù",
        difficulty = 2,
        intimacy = 3,
        intensity = 4,
        description = "A è sdraiata sulla schiena: una gamba resta distesa, l'altra si appoggia sulla spalla di B, che è in ginocchio davanti a lei con il busto eretto.",
        tip = "Cambiate gamba a metà: l'angolo e le sensazioni cambiano completamente.",
    ),
    Position(
        id = "granchio",
        name = "Il Granchio",
        image = R.drawable.pos_granchio,
        tagline = "Guardarsi mentre succede",
        difficulty = 2,
        intimacy = 3,
        intensity = 3,
        description = "Seduti uno di fronte all'altra, entrambi inclinati all'indietro e appoggiati sulle mani. A avvicina il bacino a quello di B e passa le gambe sopra le sue.",
        tip = "Ci si muove poco e lentamente: godetevi la vista e lasciate salire la tensione.",
    ),
    Position(
        id = "slitta",
        name = "La Slitta",
        image = R.drawable.pos_slitta,
        tagline = "A pancia in giù, completamente rilassata",
        difficulty = 1,
        intimacy = 3,
        intensity = 4,
        description = "A è distesa a pancia in giù con le gambe unite. B si inginocchia a cavalcioni delle sue cosce, con il busto eretto e le mani sulla sua schiena.",
        tip = "Un massaggio alla schiena prima di cominciare trasforma questa posizione in un rituale.",
    ),
    Position(
        id = "cascata",
        name = "La Cascata",
        image = R.drawable.pos_cascata,
        tagline = "Abbandonarsi all'indietro",
        difficulty = 3,
        intimacy = 3,
        intensity = 5,
        description = "B è seduto su una sedia. A è seduta a cavalcioni su di lui, di fronte, e si lascia andare all'indietro fino a sfiorare il pavimento con le mani, mentre B la tiene saldamente per i fianchi.",
        tip = "Mettete un cuscino a terra e risalite lentamente: il sangue alla testa amplifica le sensazioni.",
    ),
    Position(
        id = "cavalluccio",
        name = "Il Cavalluccio",
        image = R.drawable.pos_cavalluccio,
        tagline = "In ginocchio, incollati",
        difficulty = 2,
        intimacy = 3,
        intensity = 4,
        description = "B è in ginocchio, seduto sui talloni. A si inginocchia davanti a lui dandogli le spalle e si siede sul suo grembo, con la schiena contro il suo petto.",
        tip = "B ha le mani libere per accarezzare A ovunque mentre lei si muove.",
    ),
    Position(
        id = "preghiera",
        name = "L'Unione in Ginocchio",
        image = R.drawable.pos_preghiera,
        tagline = "Alla pari, vicinissimi",
        difficulty = 2,
        intimacy = 5,
        intensity = 3,
        description = "Entrambi in ginocchio, uno di fronte all'altra, con il busto eretto e stretti in un abbraccio. A allarga leggermente le ginocchia per accogliere B.",
        tip = "Più adatta a baci e carezze che al ritmo: usatela per rallentare e ritrovarvi.",
    ),
    Position(
        id = "mezzaluna",
        name = "La Mezzaluna",
        image = R.drawable.pos_mezzaluna,
        tagline = "Il cucchiaio che osa di più",
        difficulty = 2,
        intimacy = 4,
        intensity = 4,
        description = "Sdraiati sul fianco come nel Cucchiaio, con B dietro. A solleva la gamba superiore verso l'alto e B la sostiene con la mano.",
        tip = "La gamba sollevata lascia spazio alle mani di entrambi: approfittatene.",
    ),
    Position(
        id = "trono_regina",
        name = "Il Trono della Regina",
        image = R.drawable.pos_trono_regina,
        tagline = "Lei comodamente seduta, lui ai suoi piedi",
        difficulty = 1,
        intimacy = 4,
        intensity = 4,
        description = "A si siede sul bordo di una sedia o del letto con le gambe aperte. B si inginocchia davanti a lei e le dedica tutta l'attenzione della sua bocca.",
        tip = "A può guidare B con le mani tra i capelli: lento e costante vince sempre.",
    ),
    Position(
        id = "bacio_ginocchio",
        name = "Il Bacio in Ginocchio",
        image = R.drawable.pos_bacio_ginocchio,
        tagline = "Adorazione",
        difficulty = 1,
        intimacy = 3,
        intensity = 4,
        description = "A resta in piedi, magari appoggiata a una parete. B si inginocchia davanti a lei e usa bocca e mani per darle piacere.",
        tip = "Funziona benissimo anche a ruoli invertiti. Un cuscino sotto le ginocchia aiuta a durare.",
    ),
    Position(
        id = "banchetto",
        name = "Il Banchetto",
        image = R.drawable.pos_banchetto,
        tagline = "Solo per il suo piacere",
        difficulty = 1,
        intimacy = 4,
        intensity = 4,
        description = "A è sdraiata sulla schiena con le ginocchia piegate e aperte. B si distende a pancia in giù tra le sue gambe, con le braccia sotto le sue cosce.",
        tip = "Un cuscino sotto il bacino di A migliora l'angolo e risparmia il collo di B.",
    ),
    Position(
        id = "pressa",
        name = "La Pressa",
        image = R.drawable.pos_pressa,
        tagline = "Intensità massima",
        difficulty = 3,
        intimacy = 4,
        intensity = 5,
        description = "A è sdraiata sulla schiena e porta le ginocchia verso il petto. B si posiziona sopra di lei, sostenendosi sulle braccia tese, con le gambe di A appoggiate contro il suo petto.",
        tip = "È la più profonda di tutte: cominciate piano e parlate molto.",
    ),
    Position(
        id = "altare",
        name = "L'Altare",
        image = R.drawable.pos_altare,
        tagline = "Sollevata, offerta",
        difficulty = 2,
        intimacy = 3,
        intensity = 5,
        description = "B è in ginocchio, seduto sui talloni. A è sdraiata sulla schiena davanti a lui con il bacino sollevato e appoggiato sulle sue cosce, le gambe intorno ai suoi fianchi.",
        tip = "B ha entrambe le mani libere e una vista completa: usatele entrambe.",
    ),
    Position("inventive_69", "Il 69 Fantasioso", R.drawable.pos_inventive_69),
    Position("new_69_on_the_chair", "Il 69 sulla Sedia", R.drawable.pos_new_69_on_the_chair),
    Position("straddle", "A Cavalcioni", R.drawable.pos_straddle),
    Position("prone_bone", "A Pancia in Giù", R.drawable.pos_prone_bone),
    Position("abyss", "L'Abisso", R.drawable.pos_abyss),
    Position("aquarius", "L'Acquario", R.drawable.pos_aquarius),
    Position("acrobat", "L'Acrobata", R.drawable.pos_acrobat),
    Position("worship", "L'Adorazione", R.drawable.pos_worship),
    Position("airplane", "L'Aeroplano", R.drawable.pos_airplane),
    Position("orgazmic_penetration", "L'Affondo Orgasmico", R.drawable.pos_orgazmic_penetration),
    Position("aphrodite", "Afrodite", R.drawable.pos_aphrodite),
    Position("side_saddle", "All'Amazzone", R.drawable.pos_side_saddle),
    Position("indian_style", "All'Indiana", R.drawable.pos_indian_style),
    Position("mexican_style", "Alla Messicana", R.drawable.pos_mexican_style),
    Position("military_style", "Alla Militare", R.drawable.pos_military_style),
    Position("workout", "L'Allenamento", R.drawable.pos_workout),
    Position("el_columpio", "L'Altalena", R.drawable.pos_el_columpio),
    Position("speaker", "L'Altoparlante", R.drawable.pos_speaker),
    Position("hottest_lover", "L'Amante Focoso", R.drawable.pos_hottest_lover),
    Position("anaconda", "L'Anaconda", R.drawable.pos_anaconda),
    Position("loop", "L'Anello", R.drawable.pos_loop),
    Position("amphibian", "L'Anfibio", R.drawable.pos_amphibian),
    Position("snow_angel", "L'Angelo di Neve", R.drawable.pos_snow_angel),
    Position("anna", "Anna", R.drawable.pos_anna),
    Position("watering_can", "L'Annaffiatoio", R.drawable.pos_watering_can),
    Position("apollo", "Apollo", R.drawable.pos_apollo),
    Position("appetite", "L'Appetito", R.drawable.pos_appetite),
    Position("eagle", "L'Aquila", R.drawable.pos_eagle),
    Position("spread_eagle", "L'Aquila ad Ali Spiegate", R.drawable.pos_spread_eagle),
    Position("plow", "L'Aratro", R.drawable.pos_plow),
    Position("arch", "L'Arco", R.drawable.pos_arch),
    Position("rainbow", "L'Arcobaleno", R.drawable.pos_rainbow),
    Position("aries", "L'Ariete", R.drawable.pos_aries),
    Position("harmony", "L'Armonia", R.drawable.pos_harmony),
    Position("harp", "L'Arpa", R.drawable.pos_harp),
    Position("chinese_art", "L'Arte Cinese", R.drawable.pos_chinese_art),
    Position("fantastic_elevator", "L'Ascensore Fantastico", R.drawable.pos_fantastic_elevator),
    Position("weightlessness", "L'Assenza di Gravità", R.drawable.pos_weightlessness),
    Position("asteroid", "L'Asteroide", R.drawable.pos_asteroid),
    Position("astrologer", "L'Astrologo", R.drawable.pos_astrologer),
    Position("case", "L'Astuccio", R.drawable.pos_case),
    Position("soft_landing", "L'Atterraggio Morbido", R.drawable.pos_soft_landing),
    Position("adventurer", "L'Avventuriero", R.drawable.pos_adventurer),
    Position("french_kiss", "Il Bacio alla Francese", R.drawable.pos_french_kiss),
    Position("ballet_dancer", "La Ballerina", R.drawable.pos_ballet_dancer),
    Position("splitting_bamboo", "Il Bambù Spezzato", R.drawable.pos_splitting_bamboo),
    Position("banana_split", "La Banana Split", R.drawable.pos_banana_split),
    Position("barbie", "Barbie", R.drawable.pos_barbie),
    Position("boat", "La Barca", R.drawable.pos_boat),
    Position("basset_hound", "Il Bassotto", R.drawable.pos_basset_hound),
    Position("staff", "Il Bastone", R.drawable.pos_staff),
    Position("clapper", "Il Batacchio", R.drawable.pos_clapper),
    Position("batman", "Batman", R.drawable.pos_batman),
    Position("downstroke", "La Battuta", R.drawable.pos_downstroke),
    Position("sleeping_beauty", "La Bella Addormentata", R.drawable.pos_sleeping_beauty),
    Position("nice_talk", "La Bella Chiacchierata", R.drawable.pos_nice_talk),
    Position("flexible_beauty", "La Bella Flessuosa", R.drawable.pos_flexible_beauty),
    Position("pleasure_bible", "La Bibbia del Piacere", R.drawable.pos_pleasure_bible),
    Position("bicycle", "La Bicicletta", R.drawable.pos_bicycle),
    Position("libra", "La Bilancia", R.drawable.pos_libra),
    Position("barbell", "Il Bilanciere", R.drawable.pos_barbell),
    Position("seesaw", "Il Bilico", R.drawable.pos_seesaw),
    Position("bizet", "Bizet", R.drawable.pos_bizet),
    Position("hot_carl", "Il Bollente Carl", R.drawable.pos_hot_carl),
    Position("bomb", "La Bomba", R.drawable.pos_bomb),
    Position("breeze", "La Brezza", R.drawable.pos_breeze),
    Position("brute", "Il Bruto", R.drawable.pos_brute),
    Position("bulldog", "Il Bulldog", R.drawable.pos_bulldog),
    Position("tea_bag", "La Bustina di Tè", R.drawable.pos_tea_bag),
    Position("tea_bag_2", "La Bustina di Tè II", R.drawable.pos_tea_bag_2),
    Position("screwdriver", "Il Cacciavite", R.drawable.pos_screwdriver),
    Position("fall", "La Caduta", R.drawable.pos_fall),
    Position("donkey_punch", "Il Calcio dell'Asino", R.drawable.pos_donkey_punch),
    Position("chameleon", "Il Camaleonte", R.drawable.pos_chameleon),
    Position("truck", "Il Camion", R.drawable.pos_truck),
    Position("canadian", "La Canadese", R.drawable.pos_canadian),
    Position("cancer", "Il Cancro", R.drawable.pos_cancer),
    Position("el_candelabro", "Il Candelabro", R.drawable.pos_el_candelabro),
    Position("lazy_dog", "Il Cane Pigro", R.drawable.pos_lazy_dog),
    Position("captain", "Il Capitano", R.drawable.pos_captain),
    Position("brazilian_capoeira", "La Capoeira Brasiliana", R.drawable.pos_brazilian_capoeira),
    Position("overturned", "La Capovolta", R.drawable.pos_overturned),
    Position("hood", "Il Cappuccio", R.drawable.pos_hood),
    Position("capricorn", "Il Capricorno", R.drawable.pos_capricorn),
    Position("caramel", "Il Caramello", R.drawable.pos_caramel),
    Position("wheelbarrow_2", "La Carriola II", R.drawable.pos_wheelbarrow_2),
    Position("niagara_falls", "Le Cascate del Niagara", R.drawable.pos_niagara_falls),
    Position("pie_in_the_sky", "Il Castello in Aria", R.drawable.pos_pie_in_the_sky),
    Position("la_catapulta", "La Catapulta", R.drawable.pos_la_catapulta),
    Position("overpass", "Il Cavalcavia", R.drawable.pos_overpass),
    Position("knight", "Il Cavaliere", R.drawable.pos_knight),
    Position("air_rider", "Il Cavaliere dell'Aria", R.drawable.pos_air_rider),
    Position("grasshopper", "La Cavalletta", R.drawable.pos_grasshopper),
    Position("leapfrog", "La Cavallina", R.drawable.pos_leapfrog),
    Position("el_balancin", "Il Cavallo a Dondolo", R.drawable.pos_el_balancin),
    Position("sea_horse", "Il Cavalluccio Marino", R.drawable.pos_sea_horse),
    Position("el_sacacorchos", "Il Cavatappi", R.drawable.pos_el_sacacorchos),
    Position("cave", "La Caverna", R.drawable.pos_cave),
    Position("circle", "Il Cerchio", R.drawable.pos_circle),
    Position("basket", "Il Cesto", R.drawable.pos_basket),
    Position("chef", "Lo Chef", R.drawable.pos_chef),
    Position("moonlight", "Il Chiaro di Luna", R.drawable.pos_moonlight),
    Position("chibi", "Il Chibi", R.drawable.pos_chibi),
    Position("spanish_guitar", "La Chitarra Spagnola", R.drawable.pos_spanish_guitar),
    Position("belt", "La Cintura", R.drawable.pos_belt),
    Position("milk_chocolate", "Il Cioccolato al Latte", R.drawable.pos_milk_chocolate),
    Position("la_cobra", "Il Cobra", R.drawable.pos_la_cobra),
    Position("jamaican_cocktail", "Il Cocktail Giamaicano", R.drawable.pos_jamaican_cocktail),
    Position("scorpion", "La Coda dello Scorpione", R.drawable.pos_scorpion),
    Position("en_vilo", "Col Fiato Sospeso", R.drawable.pos_en_vilo),
    Position("special_breakfast", "La Colazione Speciale", R.drawable.pos_special_breakfast),
    Position("hummingbird", "Il Colibrì", R.drawable.pos_hummingbird),
    Position("hill", "La Collina", R.drawable.pos_hill),
    Position("column", "La Colonna", R.drawable.pos_column),
    Position("sucker_punch", "Il Colpo a Sorpresa", R.drawable.pos_sucker_punch),
    Position("backshot", "Il Colpo da Dietro", R.drawable.pos_backshot),
    Position("deep_stick", "Il Colpo Profondo", R.drawable.pos_deep_stick),
    Position("compliment", "Il Complimento", R.drawable.pos_compliment),
    Position("shell", "La Conchiglia", R.drawable.pos_shell),
    Position("seashell", "La Conchiglia di Mare", R.drawable.pos_seashell),
    Position("concubine", "La Concubina", R.drawable.pos_concubine),
    Position("reverse_connection", "La Connessione Inversa", R.drawable.pos_reverse_connection),
    Position("conqueror", "Il Conquistatore", R.drawable.pos_conqueror),
    Position("female_peasant", "La Contadina", R.drawable.pos_female_peasant),
    Position("contortionist", "La Contorsionista", R.drawable.pos_contortionist),
    Position("counterblow", "Il Contraccolpo", R.drawable.pos_counterblow),
    Position("rear_admiral", "Il Contrammiraglio", R.drawable.pos_rear_admiral),
    Position("bowstring", "La Corda dell'Arco", R.drawable.pos_bowstring),
    Position("courtesan", "La Cortigiana", R.drawable.pos_courtesan),
    Position("tantric_cosmo", "Il Cosmo Tantrico", R.drawable.pos_tantric_cosmo),
    Position("cowboy", "Il Cowboy", R.drawable.pos_cowboy),
    Position("reverse_cowboy", "Il Cowboy al Contrario", R.drawable.pos_reverse_cowboy),
    Position("la_vaquera", "La Cowgirl", R.drawable.pos_la_vaquera),
    Position("backwards_cowgirl", "La Cowgirl al Contrario", R.drawable.pos_backwards_cowgirl),
    Position("bent_cowgirl", "La Cowgirl Piegata", R.drawable.pos_bent_cowgirl),
    Position("cowgirl_on_the_table", "La Cowgirl sul Tavolo", R.drawable.pos_cowgirl_on_the_table),
    Position("necktie", "La Cravatta", R.drawable.pos_necktie),
    Position("barberry", "Il Crespino", R.drawable.pos_barberry),
    Position("jack", "Il Cric", R.drawable.pos_jack),
    Position("crucifixion", "La Croce", R.drawable.pos_crucifixion),
    Position("croissant", "Il Croissant", R.drawable.pos_croissant),
    Position("creme_brulee", "La Crème Brûlée", R.drawable.pos_creme_brulee),
    Position("ribbon_reverse_spoon", "Il Cucchiaio Rovesciato", R.drawable.pos_ribbon_reverse_spoon),
    Position("kitchen", "La Cucina", R.drawable.pos_kitchen),
    Position("cradle", "La Culla", R.drawable.pos_cradle),
    Position("apex", "Il Culmine", R.drawable.pos_apex),
    Position("wedge", "Il Cuneo", R.drawable.pos_wedge),
    Position("curiosity", "La Curiosità", R.drawable.pos_curiosity),
    Position("keeper", "Il Custode", R.drawable.pos_keeper),
    Position("goddess", "La Dea", R.drawable.pos_goddess),
    Position("dolphin", "Il Delfino", R.drawable.pos_dolphin),
    Position("nasty_desire", "Il Desiderio Sfacciato", R.drawable.pos_nasty_desire),
    Position("diamond", "Il Diamante", R.drawable.pos_diamond),
    Position("dirty_dancing", "Dirty Dancing", R.drawable.pos_dirty_dancing),
    Position("descent", "La Discesa", R.drawable.pos_descent),
    Position("disco", "La Discoteca", R.drawable.pos_disco),
    Position("sweet_pussy", "Il Dolce Nettare", R.drawable.pos_sweet_pussy),
    Position("sweet_sin", "Il Dolce Peccato", R.drawable.pos_sweet_sin),
    Position("tamer", "Il Domatore", R.drawable.pos_tamer),
    Position("swing", "Il Dondolio", R.drawable.pos_swing),
    Position("swing_2", "Il Dondolio II", R.drawable.pos_swing_2),
    Position("ladies_man", "Il Dongiovanni", R.drawable.pos_ladies_man),
    Position("backstroke", "Il Dorso", R.drawable.pos_backstroke),
    Position("dragon", "Il Drago", R.drawable.pos_dragon),
    Position("dejavu", "Il Déjà-vu", R.drawable.pos_dejavu),
    Position("ebony", "L'Ebano", R.drawable.pos_ebony),
    Position("elephant", "L'Elefante", R.drawable.pos_elephant),
    Position("propeller", "L'Elica", R.drawable.pos_propeller),
    Position("helicopter", "L'Elicottero", R.drawable.pos_helicopter),
    Position("emmanuel", "Emmanuelle", R.drawable.pos_emmanuel),
    Position("equilibrium", "L'Equilibrio", R.drawable.pos_equilibrium),
    Position("ecstasy", "L'Estasi", R.drawable.pos_ecstasy),
    Position("hunger", "La Fame", R.drawable.pos_hunger),
    Position("fantasy", "La Fantasia", R.drawable.pos_fantasy),
    Position("jockey", "Il Fantino", R.drawable.pos_jockey),
    Position("fairy", "La Fata", R.drawable.pos_fairy),
    Position("x_factor", "Il Fattore X", R.drawable.pos_x_factor),
    Position("special_fellatio", "La Fellatio Speciale", R.drawable.pos_special_fellatio),
    Position("iron", "Il Ferro", R.drawable.pos_iron),
    Position("birthday_party", "La Festa di Compleanno", R.drawable.pos_birthday_party),
    Position("flame", "La Fiamma", R.drawable.pos_flame),
    Position("throat_swab", "Fino in Gola", R.drawable.pos_throat_swab),
    Position("accordion", "La Fisarmonica", R.drawable.pos_accordion),
    Position("spork", "La Forchetta", R.drawable.pos_spork),
    Position("v_formation", "La Formazione a V", R.drawable.pos_v_formation),
    Position("dutch_oven", "Il Forno Olandese", R.drawable.pos_dutch_oven),
    Position("g_force", "La Forza G", R.drawable.pos_g_force),
    Position("forbidden_fruit", "Il Frutto Proibito", R.drawable.pos_forbidden_fruit),
    Position("fulcrum", "Il Fulcro", R.drawable.pos_fulcrum),
    Position("full_nelson", "La Full Nelson", R.drawable.pos_full_nelson),
    Position("fireworks", "I Fuochi d'Artificio", R.drawable.pos_fireworks),
    Position("fusion", "La Fusione", R.drawable.pos_fusion),
    Position("legs_in_the_air", "Gambe all'Aria", R.drawable.pos_legs_in_the_air),
    Position("legs_on_shoulders", "Gambe sulle Spalle", R.drawable.pos_legs_on_shoulders),
    Position("cat", "La Gatta", R.drawable.pos_cat),
    Position("ice_cream", "Il Gelato", R.drawable.pos_ice_cream),
    Position("twins", "Le Gemelle", R.drawable.pos_twins),
    Position("gemini", "I Gemelli", R.drawable.pos_gemini),
    Position("moan", "Il Gemito", R.drawable.pos_moan),
    Position("orgazm_generator", "Il Generatore di Orgasmi", R.drawable.pos_orgazm_generator),
    Position("sprout", "Il Germoglio", R.drawable.pos_sprout),
    Position("guillotine", "La Ghigliottina", R.drawable.pos_guillotine),
    Position("japan", "Il Giappone", R.drawable.pos_japan),
    Position("exciting_game", "Il Gioco Eccitante", R.drawable.pos_exciting_game),
    Position("young_stallion", "Il Giovane Stallone", R.drawable.pos_young_stallion),
    Position("giraffe", "La Giraffa", R.drawable.pos_giraffe),
    Position("pinwheel", "La Girandola", R.drawable.pos_pinwheel),
    Position("julia", "Giulia", R.drawable.pos_julia),
    Position("gorge", "La Gola", R.drawable.pos_gorge),
    Position("deep_throat", "La Gola Profonda", R.drawable.pos_deep_throat),
    Position("eraser", "La Gomma", R.drawable.pos_eraser),
    Position("crab", "Il Granchio Rovesciato", R.drawable.pos_crab),
    Position("tangle", "Il Groviglio", R.drawable.pos_tangle),
    Position("watch", "La Guardia", R.drawable.pos_watch),
    Position("star_wars", "Guerre Stellari", R.drawable.pos_star_wars),
    Position("la_amazona", "La Guerriera", R.drawable.pos_la_amazona),
    Position("fallen_warrior", "Il Guerriero Caduto", R.drawable.pos_fallen_warrior),
    Position("mexican_halloween", "L'Halloween Messicano", R.drawable.pos_mexican_halloween),
    Position("chili_dog", "L'Hot Dog Piccante", R.drawable.pos_chili_dog),
    Position("houdini", "Houdini", R.drawable.pos_houdini),
    Position("hucklebuck", "L'Hucklebuck", R.drawable.pos_hucklebuck),
    Position("awesome_idea", "L'Idea Geniale", R.drawable.pos_awesome_idea),
    Position("idyll", "L'Idillio", R.drawable.pos_idyll),
    Position("fire_hydrant", "L'Idrante", R.drawable.pos_fire_hydrant),
    Position("plumber", "L'Idraulico", R.drawable.pos_plumber),
    Position("snake_charmer", "L'Incantatrice di Serpenti", R.drawable.pos_snake_charmer),
    Position("amazing_meeting", "L'Incontro Straordinario", R.drawable.pos_amazing_meeting),
    Position("secret_entrance", "L'Ingresso Segreto", R.drawable.pos_secret_entrance),
    Position("inquisitor", "L'Inquisitore", R.drawable.pos_inquisitor),
    Position("insatiable_clitoris", "L'Insaziabile", R.drawable.pos_insatiable_clitoris),
    Position("inseminator", "L'Inseminatore", R.drawable.pos_inseminator),
    Position("iris", "L'Iris", R.drawable.pos_iris),
    Position("desert_island", "L'Isola Deserta", R.drawable.pos_desert_island),
    Position("joystick", "Il Joystick", R.drawable.pos_joystick),
    Position("khaleesi", "Khaleesi", R.drawable.pos_khaleesi),
    Position("ladyboy", "La Lady", R.drawable.pos_ladyboy),
    Position("blade", "La Lama", R.drawable.pos_blade),
    Position("italian_chandelier", "Il Lampadario Italiano", R.drawable.pos_italian_chandelier),
    Position("pointer", "La Lancetta", R.drawable.pos_pointer),
    Position("leo", "Il Leone", R.drawable.pos_leo),
    Position("leopard", "Il Leopardo", R.drawable.pos_leopard),
    Position("deck_chair", "Il Lettino", R.drawable.pos_deck_chair),
    Position("liana", "La Liana", R.drawable.pos_liana),
    Position("libido", "La Libido", R.drawable.pos_libido),
    Position("book", "Il Libro", R.drawable.pos_book),
    Position("straight_line", "La Linea Retta", R.drawable.pos_straight_line),
    Position("wrestling", "La Lotta", R.drawable.pos_wrestling),
    Position("lock", "Il Lucchetto", R.drawable.pos_lock),
    Position("lizard", "La Lucertola", R.drawable.pos_lizard),
    Position("louise", "Luisa", R.drawable.pos_louise),
    Position("snail", "La Lumaca", R.drawable.pos_snail),
    Position("honeymoon", "La Luna di Miele", R.drawable.pos_honeymoon),
    Position("she_wolf", "La Lupa", R.drawable.pos_she_wolf),
    Position("master", "Il Maestro", R.drawable.pos_master),
    Position("butler", "Il Maggiordomo", R.drawable.pos_butler),
    Position("feeder", "La Mangiatoia", R.drawable.pos_feeder),
    Position("praying_mantis", "La Mantide Religiosa", R.drawable.pos_praying_mantis),
    Position("marsh_mallow", "Il Marshmallow", R.drawable.pos_marsh_mallow),
    Position("thors_hammer", "Il Martello di Thor", R.drawable.pos_thors_hammer),
    Position("jackhammer", "Il Martello Pneumatico", R.drawable.pos_jackhammer),
    Position("car_mechanic", "Il Meccanico", R.drawable.pos_car_mechanic),
    Position("jellyfish", "La Medusa", R.drawable.pos_jellyfish),
    Position("midnight", "La Mezzanotte", R.drawable.pos_midnight),
    Position("mirage", "Il Miraggio", R.drawable.pos_mirage),
    Position("spring", "La Molla", R.drawable.pos_spring),
    Position("clip", "La Molletta", R.drawable.pos_clip),
    Position("la_montana_magica", "La Montagna Magica", R.drawable.pos_la_montana_magica),
    Position("tight_squeeze", "La Morsa", R.drawable.pos_tight_squeeze),
    Position("narcissus", "Il Narciso", R.drawable.pos_narcissus),
    Position("nirvana", "Il Nirvana", R.drawable.pos_nirvana),
    Position("knot", "Il Nodo", R.drawable.pos_knot),
    Position("rare_trick", "Il Numero Raro", R.drawable.pos_rare_trick),
    Position("oasis", "L'Oasi", R.drawable.pos_oasis),
    Position("flying_dutchman", "L'Olandese Volante", R.drawable.pos_flying_dutchman),
    Position("olympus", "L'Olimpo", R.drawable.pos_olympus),
    Position("stick_figure", "L'Omino Stilizzato", R.drawable.pos_stick_figure),
    Position("orchid", "L'Orchidea", R.drawable.pos_orchid),
    Position("rabbit_ears", "Le Orecchie da Coniglio", R.drawable.pos_rabbit_ears),
    Position("clock", "L'Orologio", R.drawable.pos_clock),
    Position("hostage", "L'Ostaggio", R.drawable.pos_hostage),
    Position("ball", "La Palla", R.drawable.pos_ball),
    Position("bench", "La Panchina", R.drawable.pos_bench),
    Position("low_start", "La Partenza dai Blocchi", R.drawable.pos_low_start),
    Position("reverse_doggy", "La Pecorina al Contrario", R.drawable.pos_reverse_doggy),
    Position("low_doggy", "La Pecorina Bassa", R.drawable.pos_low_doggy),
    Position("passive_doggy", "La Pecorina Passiva", R.drawable.pos_passive_doggy),
    Position("crazy_doggy", "La Pecorina Pazza", R.drawable.pos_crazy_doggy),
    Position("doggy_on_the_edge", "La Pecorina sul Bordo", R.drawable.pos_doggy_on_the_edge),
    Position("doggy_on_the_edge_2", "La Pecorina sul Bordo II", R.drawable.pos_doggy_on_the_edge_2),
    Position("slope", "Il Pendio", R.drawable.pos_slope),
    Position("pearl", "La Perla", R.drawable.pos_pearl),
    Position("juicy_ass", "La Pesca", R.drawable.pos_juicy_ass),
    Position("pisces", "I Pesci", R.drawable.pos_pisces),
    Position("multiply_pleasure", "Il Piacere Moltiplicato", R.drawable.pos_multiply_pleasure),
    Position("venus_flytrap", "La Pianta Carnivora", R.drawable.pos_venus_flytrap),
    Position("plain", "La Pianura", R.drawable.pos_plain),
    Position("spicy_dish", "Il Piatto Piccante", R.drawable.pos_spicy_dish),
    Position("nosedive", "La Picchiata", R.drawable.pos_nosedive),
    Position("penguin", "Il Pinguino", R.drawable.pos_penguin),
    Position("pioneer", "Il Pioniere", R.drawable.pos_pioneer),
    Position("poplar", "Il Pioppo", R.drawable.pos_poplar),
    Position("angry_pirate", "Il Pirata Furioso", R.drawable.pos_angry_pirate),
    Position("python", "Il Pitone", R.drawable.pos_python),
    Position("lace", "Il Pizzo", R.drawable.pos_lace),
    Position("plaid", "Il Plaid", R.drawable.pos_plaid),
    Position("plank", "La Plancia", R.drawable.pos_plank),
    Position("playboy", "Il Playboy", R.drawable.pos_playboy),
    Position("pokemon", "Il Pokémon", R.drawable.pos_pokemon),
    Position("octopus", "Il Polpo", R.drawable.pos_octopus),
    Position("fireman", "Il Pompiere", R.drawable.pos_fireman),
    Position("london_bridge", "Il Ponte di Londra", R.drawable.pos_london_bridge),
    Position("wild_pony", "Il Pony Selvaggio", R.drawable.pos_wild_pony),
    Position("back_door", "La Porta sul Retro", R.drawable.pos_back_door),
    Position("erotic_poster", "Il Poster Erotico", R.drawable.pos_erotic_poster),
    Position("comfortable_place", "Il Posto Comodo", R.drawable.pos_comfortable_place),
    Position("hot_lunch", "Il Pranzo Caldo", R.drawable.pos_hot_lunch),
    Position("precipice", "Il Precipizio", R.drawable.pos_precipice),
    Position("delicacy", "La Prelibatezza", R.drawable.pos_delicacy),
    Position("juego_previo", "I Preliminari", R.drawable.pos_juego_previo),
    Position("catch", "La Presa", R.drawable.pos_catch),
    Position("chairman", "Il Presidente", R.drawable.pos_chairman),
    Position("el_pretzel", "Il Pretzel", R.drawable.pos_el_pretzel),
    Position("captivity", "La Prigionia", R.drawable.pos_captivity),
    Position("valedictorian", "Il Primo della Classe", R.drawable.pos_valedictorian),
    Position("princess", "La Principessa", R.drawable.pos_princess),
    Position("depth", "La Profondità", R.drawable.pos_depth),
    Position("pterodactyl", "Lo Pterodattilo", R.drawable.pos_pterodactyl),
    Position("punishment", "La Punizione", R.drawable.pos_punishment),
    Position("puzzle", "Il Puzzle", R.drawable.pos_puzzle),
    Position("ghetto", "Il Quartiere", R.drawable.pos_ghetto),
    Position("fifth_element", "Il Quinto Elemento", R.drawable.pos_fifth_element),
    Position("spider", "Il Ragno", R.drawable.pos_spider),
    Position("kinky_spider", "Il Ragno Malizioso", R.drawable.pos_kinky_spider),
    Position("launch_pad", "La Rampa di Lancio", R.drawable.pos_launch_pad),
    Position("frog", "La Ranocchia", R.drawable.pos_frog),
    Position("rocket", "Il Razzo", R.drawable.pos_rocket),
    Position("relaxation", "Il Relax", R.drawable.pos_relaxation),
    Position("close_breathing", "Respiro a Respiro", R.drawable.pos_close_breathing),
    Position("recharge", "La Ricarica", R.drawable.pos_recharge),
    Position("reflection", "Il Riflesso", R.drawable.pos_reflection),
    Position("tugboat", "Il Rimorchiatore", R.drawable.pos_tugboat),
    Position("riverside", "La Riva del Fiume", R.drawable.pos_riverside),
    Position("revelation", "La Rivelazione", R.drawable.pos_revelation),
    Position("rodeo", "Il Rodeo", R.drawable.pos_rodeo),
    Position("rose", "La Rosa", R.drawable.pos_rose),
    Position("woven_rose", "La Rosa Intrecciata", R.drawable.pos_woven_rose),
    Position("russian_roulette", "La Roulette Russa", R.drawable.pos_russian_roulette),
    Position("mountain_creek", "Il Ruscello di Montagna", R.drawable.pos_mountain_creek),
    Position("waterfall", "Il Salto d'Acqua", R.drawable.pos_waterfall),
    Position("froggy_style", "Il Salto della Rana", R.drawable.pos_froggy_style),
    Position("st_valentines_day", "San Valentino", R.drawable.pos_st_valentines_day),
    Position("satyr", "Il Satiro", R.drawable.pos_satyr),
    Position("discharge", "La Scarica", R.drawable.pos_discharge),
    Position("funny_joke", "Lo Scherzo", R.drawable.pos_funny_joke),
    Position("sex_slave", "La Schiava d'Amore", R.drawable.pos_sex_slave),
    Position("backrest", "Lo Schienale", R.drawable.pos_backrest),
    Position("ape", "La Scimmia", R.drawable.pos_ape),
    Position("crazy_monkey", "La Scimmia Pazza", R.drawable.pos_crazy_monkey),
    Position("spider_monkey", "La Scimmia Ragno", R.drawable.pos_spider_monkey),
    Position("spark", "La Scintilla", R.drawable.pos_spark),
    Position("slide", "Lo Scivolo", R.drawable.pos_slide),
    Position("flying_squirrel", "Lo Scoiattolo Volante", R.drawable.pos_flying_squirrel),
    Position("scorpio", "Lo Scorpione", R.drawable.pos_scorpio),
    Position("shocker", "La Scossa", R.drawable.pos_shocker),
    Position("casket", "Lo Scrigno", R.drawable.pos_casket),
    Position("apologies", "Le Scuse", R.drawable.pos_apologies),
    Position("prison_guard", "Il Secondino", R.drawable.pos_prison_guard),
    Position("la_silla_de_la_reina", "La Sedia della Regina", R.drawable.pos_la_silla_de_la_reina),
    Position("soft_chair", "La Sedia Morbida", R.drawable.pos_soft_chair),
    Position("vulgar_chair", "La Sedia Sfacciata", R.drawable.pos_vulgar_chair),
    Position("saddle", "La Sella", R.drawable.pos_saddle),
    Position("sower", "Il Seminatore", R.drawable.pos_sower),
    Position("lazy_evening", "La Serata Pigra", R.drawable.pos_lazy_evening),
    Position("snake", "Il Serpente", R.drawable.pos_snake),
    Position("sexo_oral_pene", "Il Sesso Orale", R.drawable.pos_sexo_oral_pene),
    Position("thirst", "La Sete", R.drawable.pos_thirst),
    Position("sphinx", "La Sfinge Egizia", R.drawable.pos_sphinx),
    Position("las_tijeras", "La Sforbiciata", R.drawable.pos_las_tijeras),
    Position("look_to_the_sky", "Lo Sguardo al Cielo", R.drawable.pos_look_to_the_sky),
    Position("silence", "Il Silenzio", R.drawable.pos_silence),
    Position("symphony", "La Sinfonia", R.drawable.pos_symphony),
    Position("mermaid", "La Sirena", R.drawable.pos_mermaid),
    Position("sledge", "Lo Slittino", R.drawable.pos_sledge),
    Position("dream", "Il Sogno", R.drawable.pos_dream),
    Position("soldier", "Il Soldato", R.drawable.pos_soldier),
    Position("source", "La Sorgente", R.drawable.pos_source),
    Position("holder", "Il Sostegno", R.drawable.pos_holder),
    Position("submissive", "La Sottomessa", R.drawable.pos_submissive),
    Position("skewer", "Lo Spiedo", R.drawable.pos_skewer),
    Position("shining", "Lo Splendore", R.drawable.pos_shining),
    Position("dirty_sanchez", "Lo Sporco Sanchez", R.drawable.pos_dirty_sanchez),
    Position("shameless", "La Spudorata", R.drawable.pos_shameless),
    Position("snack", "Lo Spuntino", R.drawable.pos_snack),
    Position("t_square", "La Squadra", R.drawable.pos_t_square),
    Position("hard_worker", "Lo Stacanovista", R.drawable.pos_hard_worker),
    Position("starfish", "La Stella Marina", R.drawable.pos_starfish),
    Position("unique_styles", "Lo Stile Unico", R.drawable.pos_unique_styles),
    Position("weird_fantasy", "La Strana Fantasia", R.drawable.pos_weird_fantasy),
    Position("tight_pussy", "Stretta Stretta", R.drawable.pos_tight_pussy),
    Position("stuntman", "Lo Stuntman", R.drawable.pos_stuntman),
    Position("gimlet", "Il Succhiello", R.drawable.pos_gimlet),
    Position("nun", "La Suora", R.drawable.pos_nun),
    Position("superhero", "Il Supereroe", R.drawable.pos_superhero),
    Position("superman", "Superman", R.drawable.pos_superman),
    Position("supernova", "La Supernova", R.drawable.pos_supernova),
    Position("superwoman", "Superwoman", R.drawable.pos_superwoman),
    Position("whisper", "Il Sussurro", R.drawable.pos_whisper),
    Position("drum", "Il Tamburo", R.drawable.pos_drum),
    Position("tango", "Il Tango", R.drawable.pos_tango),
    Position("tantra", "Il Tantra", R.drawable.pos_tantra),
    Position("magic_carpet", "Il Tappeto Volante", R.drawable.pos_magic_carpet),
    Position("bung", "Il Tappo", R.drawable.pos_bung),
    Position("turtle", "La Tartaruga", R.drawable.pos_turtle),
    Position("surf_board", "La Tavola da Surf", R.drawable.pos_surf_board),
    Position("coffee_table", "Il Tavolino", R.drawable.pos_coffee_table),
    Position("temptation", "La Tentazione", R.drawable.pos_temptation),
    Position("tiara", "La Tiara", R.drawable.pos_tiara),
    Position("crouching_tiger", "La Tigre Accovacciata", R.drawable.pos_crouching_tiger),
    Position("shy_girl", "La Timida", R.drawable.pos_shy_girl),
    Position("tiramisu", "Il Tiramisù", R.drawable.pos_tiramisu),
    Position("tug_of_war", "Il Tiro alla Fune", R.drawable.pos_tug_of_war),
    Position("titanic", "Il Titanic", R.drawable.pos_titanic),
    Position("titanic_2", "Il Titanic II", R.drawable.pos_titanic_2),
    Position("sensual_touch", "Il Tocco Sensuale", R.drawable.pos_sensual_touch),
    Position("torch", "La Torcia", R.drawable.pos_torch),
    Position("bullfighter", "Il Torero", R.drawable.pos_bullfighter),
    Position("tornado", "Il Tornado", R.drawable.pos_tornado),
    Position("eiffel_tower", "La Torre Eiffel", R.drawable.pos_eiffel_tower),
    Position("american_pie", "La Torta Americana", R.drawable.pos_american_pie),
    Position("spanish_sunset", "Il Tramonto Spagnolo", R.drawable.pos_spanish_sunset),
    Position("train", "Il Treno", R.drawable.pos_train),
    Position("crazy_train", "Il Treno Impazzito", R.drawable.pos_crazy_train),
    Position("bermuda_triangle", "Il Triangolo delle Bermuda", R.drawable.pos_bermuda_triangle),
    Position("triceratops", "Il Triceratopo", R.drawable.pos_triceratops),
    Position("trunk", "Il Tronco", R.drawable.pos_trunk),
    Position("iron_throne", "Il Trono di Spade", R.drawable.pos_iron_throne),
    Position("dive", "Il Tuffo", R.drawable.pos_dive),
    Position("tulip", "Il Tulipano", R.drawable.pos_tulip),
    Position("twerk_on_dick", "Il Twerk", R.drawable.pos_twerk_on_dick),
    Position("unicorn", "L'Unicorno", R.drawable.pos_unicorn),
    Position("merger", "L'Unione", R.drawable.pos_merger),
    Position("spiderman", "L'Uomo Ragno", R.drawable.pos_spiderman),
    Position("holiday", "La Vacanza", R.drawable.pos_holiday),
    Position("avalanche", "La Valanga", R.drawable.pos_avalanche),
    Position("venus", "Venere", R.drawable.pos_venus),
    Position("el_ventilador", "Il Ventilatore", R.drawable.pos_el_ventilador),
    Position("virgo", "La Vergine", R.drawable.pos_virgo),
    Position("alley", "Il Vicolo", R.drawable.pos_alley),
    Position("cello", "Il Violoncello", R.drawable.pos_cello),
    Position("el_tornillo", "La Vite", R.drawable.pos_el_tornillo),
    Position("victory", "La Vittoria", R.drawable.pos_victory),
    Position("need_for_speed", "Voglia di Velocità", R.drawable.pos_need_for_speed),
    Position("night_fly", "Il Volo Notturno", R.drawable.pos_night_fly),
    Position("xxx", "XXX", R.drawable.pos_xxx),
    Position("yin_yang", "Yin e Yang", R.drawable.pos_yin_yang),
    Position("wild_yoga", "Lo Yoga Selvaggio", R.drawable.pos_wild_yoga),
    Position("butter_churner", "La Zangola", R.drawable.pos_butter_churner),
    Position("zeus", "Zeus", R.drawable.pos_zeus),
    Position("zodiac", "Lo Zodiaco", R.drawable.pos_zodiac),
    Position("zombie", "Lo Zombie", R.drawable.pos_zombie),
)
