#!/usr/bin/env python3
"""Sorgente delle posizioni del Kamasutra.

Genera app/src/main/java/com/funcouple/app/Positions.kt e, se c'è la cartella
assets-kamasutra/ (non versionata: si estrae da assets-kamasutra.zip), prepara le
illustrazioni in app/src/main/res/drawable-nodpi/pos_<id>.webp. Per le immagini serve Pillow.

Le prime posizioni hanno una scheda completa; le altre (EXTRA) solo nome e illustrazione.
Ogni posizione indica con "img" il nome dell'illustrazione originale (imgi_<n>_<img>.png).
Gli originali hanno sfondo bianco e figure rosa e blu: qui lo sfondo diventa trasparente,
il blu diventa il viola dell'app e gli arredi grigi diventano chiari, per il tema scuro.
A è la figura rosa (chi accoglie), B quella viola (chi penetra).
"""
import colorsys
import glob
import os
import re
from multiprocessing import Pool

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "app/src/main/java/com/funcouple/app/Positions.kt")
ASSETS = os.path.join(ROOT, "assets-kamasutra")
DRAWABLES = os.path.join(ROOT, "app/src/main/res/drawable-nodpi")

POSITIONS = [
    dict(id="missionario", name="Il Missionario", tag="Il grande classico, occhi negli occhi", d=1, i=5, x=2,
         desc="A si sdraia sulla schiena con le ginocchia piegate. B si distende sopra, sostenendosi sugli avambracci, petto contro petto. Il contatto visivo e i baci fanno tutto il resto.",
         tip="Un cuscino sotto il bacino di A cambia l'angolo e rende tutto molto più intenso.",
         img="el-misionero"),
    dict(id="amazzone", name="L'Amazzone", tag="Chi sta sopra detta il ritmo", d=1, i=4, x=4,
         desc="B è sdraiato sulla schiena. A si mette a cavalcioni sul suo bacino, in ginocchio e con il busto eretto, le mani appoggiate sul petto di B, e controlla profondità e velocità.",
         tip="Alternate movimenti circolari lenti a spinte più decise: l'attesa è metà del piacere.",
         img="rider"),
    dict(id="cucchiaio", name="Il Cucchiaio", tag="Lento, pigro e dolcissimo", d=1, i=5, x=2,
         desc="Entrambi sdraiati sul fianco, rivolti nella stessa direzione. B abbraccia A da dietro, i corpi aderiscono dalla testa ai piedi e i movimenti sono lenti e profondi.",
         tip="Perfetta al risveglio. La mano libera di B può esplorare tutto il corpo di A.",
         img="la-cucharita"),
    dict(id="pecorina", name="La Pecorina", tag="Istinto puro", d=1, i=2, x=5,
         desc="A si mette a quattro zampe, con la schiena leggermente inarcata. B si inginocchia dietro, le afferra i fianchi e guida il movimento.",
         tip="Se A appoggia petto e avambracci sul letto, l'angolo diventa ancora più profondo.",
         img="el-perrito"),
    dict(id="loto", name="Il Loto", tag="Abbraccio totale, respiro all'unisono", d=2, i=5, x=3,
         desc="B si siede a gambe incrociate. A si siede sul suo grembo, di fronte, avvolgendo gambe e braccia intorno al suo corpo. Ci si muove dondolando insieme.",
         tip="Sincronizzate il respiro e guardatevi negli occhi: è la posizione tantrica per eccellenza.",
         img="la-flor-de-loto"),
    dict(id="amazzone_rovesciata", name="L'Amazzone Rovesciata", tag="Uno spettacolo da non perdere", d=2, i=2, x=5,
         desc="B è sdraiato sulla schiena. A si mette a cavalcioni dandogli le spalle, appoggia le mani sulle sue cosce e si muove avanti e indietro.",
         tip="B può sollevare leggermente le ginocchia per offrire ad A un appoggio in più.",
         img="la-vaquera-invertida"),
    dict(id="incudine", name="L'Incudine", tag="Profonda e travolgente", d=2, i=3, x=5,
         desc="A è sdraiata sulla schiena e solleva le gambe fino ad appoggiarle sulle spalle di B, che è in ginocchio e si piega in avanti sostenendosi sulle mani.",
         tip="Andate per gradi: più B si piega in avanti, più la penetrazione è profonda.",
         img="anvil"),
    dict(id="trono", name="Il Trono", tag="Seduti, vicinissimi", d=1, i=3, x=3,
         desc="B si siede su una sedia robusta. A si siede sul suo grembo dandogli le spalle, con i piedi a terra, e si muove su e giù mentre B la stringe per la vita.",
         tip="Le mani di B sono libere: è il momento ideale per carezze e baci sul collo.",
         img="zeal"),
    dict(id="abbraccio_sospeso", name="L'Abbraccio Sospeso", tag="Passione senza gravità", d=3, i=4, x=5,
         desc="B è in piedi e solleva A sorreggendola sotto le cosce. A avvolge le gambe intorno ai suoi fianchi e le braccia intorno al suo collo.",
         tip="Appoggiate la schiena di A a una parete: meno fatica, più resistenza.",
         img="caliper"),
    dict(id="ponte", name="Il Ponte", tag="Per coppie acrobatiche", d=3, i=2, x=4,
         desc="B si solleva a ponte, appoggiato su mani e piedi con il ventre verso l'alto. A si mette a cavalcioni in piedi sopra il suo bacino e si abbassa quanto basta.",
         tip="Serve forza nelle braccia: provatela per poco tempo, o con un pouf sotto la schiena di B.",
         img="el-puente"),
    dict(id="carriola", name="La Carriola", tag="Divertente quanto impegnativa", d=3, i=2, x=4,
         desc="A appoggia le mani a terra mentre B, in piedi, la solleva per le cosce. A stringe le gambe intorno ai fianchi di B.",
         tip="Più facile se A appoggia gli avambracci sul bordo del letto invece che a terra.",
         img="la-carretilla"),
    dict(id="sessantanove", name="Il 69", tag="Dare e ricevere, insieme", d=2, i=4, x=4,
         desc="B è sdraiato sulla schiena. A si posiziona sopra, in direzione opposta, con le ginocchia ai lati della sua testa: ognuno dedica la bocca al piacere dell'altro.",
         tip="Provatela anche sdraiati sul fianco: più comoda e si resiste molto più a lungo.",
         img="el-69"),
    dict(id="sfinge", name="La Sfinge", tag="Pelle contro pelle", d=1, i=4, x=3,
         desc="A si sdraia a pancia in giù, sollevando appena il busto sugli avambracci. B si distende sopra la sua schiena, con le gambe all'esterno delle sue.",
         tip="Un cuscino sotto il bacino di A e baci sulla nuca: brividi garantiti.",
         img="twix"),
    dict(id="forbici", name="Le Forbici", tag="Intreccio perfetto", d=2, i=3, x=3,
         desc="Sdraiati in direzioni opposte, i due partner intrecciano le gambe come lame di forbice fino a far aderire i bacini. Ci si muove ondeggiando lentamente.",
         tip="Tenetevi per mano o per le caviglie per darvi il ritmo a vicenda.",
         img="marmalade"),
    dict(id="farfalla", name="La Farfalla", tag="Sul bordo del letto", d=2, i=3, x=5,
         desc="A si sdraia sulla schiena con il bacino sul bordo del letto e appoggia le gambe sulle spalle di B, che resta in piedi e le sostiene i fianchi.",
         tip="Regolate l'altezza con un cuscino: quando i bacini sono allineati è perfetta.",
         img="stickman"),
    dict(id="muro", name="Contro il Muro", tag="Quando non si può aspettare", d=2, i=3, x=5,
         desc="A è in piedi, leggermente piegata in avanti con le mani appoggiate alla parete. B si posiziona dietro, in piedi, e la stringe per i fianchi.",
         tip="Se c'è differenza di altezza, A può salire su un gradino o divaricare un po' le gambe.",
         img="wall"),
    dict(id="rana", name="La Rana", tag="Accovacciata, padrona del gioco", d=2, i=3, x=5,
         desc="B è sdraiato sulla schiena. A si accovaccia sopra di lui con i piedi ben piantati ai lati dei suoi fianchi e le mani sul suo petto, e molleggia su e giù.",
         tip="È faticosa per le cosce: B può sostenere A sotto i glutei per aiutarla a tenere il ritmo.",
         img="asian-cowgirl"),
    dict(id="abbraccio_amazzone", name="L'Amazzone Distesa", tag="Sopra, ma cuore a cuore", d=1, i=5, x=3,
         desc="B è sdraiato sulla schiena. A si distende su di lui, petto contro petto, con le ginocchia ai lati dei suoi fianchi, e si muove scivolando avanti e indietro.",
         tip="Movimenti piccoli e lenti: qui conta lo sfregamento, non la profondità.",
         img="shuttle"),
    dict(id="gatto", name="Il Gatto", tag="Schiena inarcata, fianchi in alto", d=1, i=2, x=5,
         desc="A è in ginocchio con il petto e le braccia distesi sul letto e i fianchi sollevati. B si inginocchia dietro di lei e la tiene per i fianchi.",
         tip="Un cuscino sotto il petto di A rende la posizione comoda anche a lungo.",
         img="downward-dog"),
    dict(id="inchino", name="L'Inchino", tag="In piedi, senza appoggi", d=2, i=2, x=5,
         desc="A è in piedi e si piega in avanti fino a toccare le caviglie o il pavimento. B resta in piedi dietro di lei e la sostiene saldamente per i fianchi.",
         tip="A può appoggiare le mani su uno sgabello basso: più equilibrio, meno tensione sulle gambe.",
         img="taurus"),
    dict(id="tavolo", name="Il Tavolo", tag="La cucina non è solo per cucinare", d=2, i=4, x=4,
         desc="A si siede sul bordo di un tavolo, appoggiandosi all'indietro su una mano. B resta in piedi di fronte a lei, che gli avvolge le gambe intorno ai fianchi.",
         tip="L'altezza giusta è quella in cui i bacini sono allineati: provate anche con il piano della cucina.",
         img="slow-dance"),
    dict(id="scrivania", name="La Scrivania", tag="Urgente e irresistibile", d=1, i=2, x=5,
         desc="A si piega in avanti e distende il busto su un tavolo o una scrivania, con i piedi a terra. B resta in piedi dietro di lei.",
         tip="Un asciugamano piegato sul bordo evita che lo spigolo dia fastidio.",
         img="mature-lady"),
    dict(id="dondolo", name="Il Dondolo", tag="Faccia a faccia sulla sedia", d=1, i=5, x=3,
         desc="B si siede su una sedia senza braccioli. A si siede a cavalcioni su di lui, guardandolo, con le braccia intorno al suo collo, e dondola avanti e indietro.",
         tip="Se A arriva con i piedi a terra può darsi la spinta e controllare tutto il movimento.",
         img="cowgirl-on-the-chair"),
    dict(id="sdraio", name="La Sdraio", tag="Rilassati, ma non troppo", d=2, i=2, x=4,
         desc="B si siede a terra con le gambe distese e il busto inclinato all'indietro, appoggiato sulle mani. A si siede sul suo grembo dandogli le spalle, con i piedi a terra.",
         tip="A può appoggiare le mani sulle ginocchia di B per spingersi e variare l'angolo.",
         img="chair"),
    dict(id="poltrona", name="La Poltrona", tag="Il divano come alleato", d=2, i=2, x=5,
         desc="A si inginocchia sul divano o su una poltrona, aggrappandosi allo schienale. B resta in piedi dietro di lei.",
         tip="Lo schienale dà ad A un appoggio perfetto per spingere all'indietro e dettare il ritmo.",
         img="amateur"),
    dict(id="candela", name="La Candela", tag="Sottosopra", d=3, i=2, x=4,
         desc="A si sdraia e solleva gambe e bacino verso l'alto, in appoggio sulle spalle, sostenendosi la schiena con le mani. B si inginocchia davanti a lei e la sorregge per le gambe.",
         tip="Tenetela per poco: è una posizione da provare per gioco, non una maratona.",
         img="bud"),
    dict(id="scivolata", name="La Scivolata", tag="Stretti dalla testa ai piedi", d=1, i=5, x=3,
         desc="A è sdraiata sulla schiena con le gambe distese e unite. B si distende sopra di lei, con le gambe all'esterno delle sue, e si muove scivolando verso l'alto e verso il basso.",
         tip="Tenere le gambe strette aumenta l'attrito e lo sfregamento: sensazioni molto intense per entrambi.",
         img="flash"),
    dict(id="ballerino", name="Il Passo di Danza", tag="In piedi, uno contro l'altra", d=2, i=4, x=4,
         desc="In piedi, faccia a faccia. A solleva una gamba e la avvolge intorno al fianco di B, che la sostiene sotto la coscia mentre lei gli si aggrappa al collo.",
         tip="Con la schiena di A contro una parete diventa molto più stabile.",
         img="sagittarius"),
    dict(id="spaccata", name="La Spaccata", tag="Una gamba su, una giù", d=2, i=3, x=4,
         desc="A è sdraiata sulla schiena: una gamba resta distesa, l'altra si appoggia sulla spalla di B, che è in ginocchio davanti a lei con il busto eretto.",
         tip="Cambiate gamba a metà: l'angolo e le sensazioni cambiano completamente.",
         img="hero"),
    dict(id="granchio", name="Il Granchio", tag="Guardarsi mentre succede", d=2, i=3, x=3,
         desc="Seduti uno di fronte all'altra, entrambi inclinati all'indietro e appoggiati sulle mani. A avvicina il bacino a quello di B e passa le gambe sopra le sue.",
         tip="Ci si muove poco e lentamente: godetevi la vista e lasciate salire la tensione.",
         img="bow"),
    dict(id="slitta", name="La Slitta", tag="A pancia in giù, completamente rilassata", d=1, i=3, x=4,
         desc="A è distesa a pancia in giù con le gambe unite. B si inginocchia a cavalcioni delle sue cosce, con il busto eretto e le mani sulla sua schiena.",
         tip="Un massaggio alla schiena prima di cominciare trasforma questa posizione in un rituale.",
         img="speed-bump"),
    dict(id="cascata", name="La Cascata", tag="Abbandonarsi all'indietro", d=3, i=3, x=5,
         desc="B è seduto su una sedia. A è seduta a cavalcioni su di lui, di fronte, e si lascia andare all'indietro fino a sfiorare il pavimento con le mani, mentre B la tiene saldamente per i fianchi.",
         tip="Mettete un cuscino a terra e risalite lentamente: il sangue alla testa amplifica le sensazioni.",
         img="watermelon"),
    dict(id="cavalluccio", name="Il Cavalluccio", tag="In ginocchio, incollati", d=2, i=3, x=4,
         desc="B è in ginocchio, seduto sui talloni. A si inginocchia davanti a lui dandogli le spalle e si siede sul suo grembo, con la schiena contro il suo petto.",
         tip="B ha le mani libere per accarezzare A ovunque mentre lei si muove.",
         img="en-silla"),
    dict(id="preghiera", name="L'Unione in Ginocchio", tag="Alla pari, vicinissimi", d=2, i=5, x=3,
         desc="Entrambi in ginocchio, uno di fronte all'altra, con il busto eretto e stretti in un abbraccio. A allarga leggermente le ginocchia per accogliere B.",
         tip="Più adatta a baci e carezze che al ritmo: usatela per rallentare e ritrovarvi.",
         img="oath"),
    dict(id="mezzaluna", name="La Mezzaluna", tag="Il cucchiaio che osa di più", d=2, i=4, x=4,
         desc="Sdraiati sul fianco come nel Cucchiaio, con B dietro. A solleva la gamba superiore verso l'alto e B la sostiene con la mano.",
         tip="La gamba sollevata lascia spazio alle mani di entrambi: approfittatene.",
         img="glass"),
    dict(id="trono_regina", name="Il Trono della Regina", tag="Lei comodamente seduta, lui ai suoi piedi", d=1, i=4, x=4,
         desc="A si siede sul bordo di una sedia o del letto con le gambe aperte. B si inginocchia davanti a lei e le dedica tutta l'attenzione della sua bocca.",
         tip="A può guidare B con le mani tra i capelli: lento e costante vince sempre.",
         img="pussy-licking"),
    dict(id="bacio_ginocchio", name="Il Bacio in Ginocchio", tag="Adorazione", d=1, i=3, x=4,
         desc="A resta in piedi, magari appoggiata a una parete. B si inginocchia davanti a lei e usa bocca e mani per darle piacere.",
         tip="Funziona benissimo anche a ruoli invertiti. Un cuscino sotto le ginocchia aiuta a durare.",
         img="licking-master"),
    dict(id="banchetto", name="Il Banchetto", tag="Solo per il suo piacere", d=1, i=4, x=4,
         desc="A è sdraiata sulla schiena con le ginocchia piegate e aperte. B si distende a pancia in giù tra le sue gambe, con le braccia sotto le sue cosce.",
         tip="Un cuscino sotto il bacino di A migliora l'angolo e risparmia il collo di B.",
         img="cleopatra"),
    dict(id="pressa", name="La Pressa", tag="Intensità massima", d=3, i=4, x=5,
         desc="A è sdraiata sulla schiena e porta le ginocchia verso il petto. B si posiziona sopra di lei, sostenendosi sulle braccia tese, con le gambe di A appoggiate contro il suo petto.",
         tip="È la più profonda di tutte: cominciate piano e parlate molto.",
         img="tight-vagina"),
    dict(id="altare", name="L'Altare", tag="Sollevata, offerta", d=2, i=3, x=5,
         desc="B è in ginocchio, seduto sui talloni. A è sdraiata sulla schiena davanti a lui con il bacino sollevato e appoggiato sulle sue cosce, le gambe intorno ai suoi fianchi.",
         tip="B ha entrambe le mani libere e una vista completa: usatele entrambe.",
         img="emperor"),
]

# Le altre illustrazioni: solo il nome, tradotto da quello del file. Finché non hanno una
# scheda completa restano senza descrizione, consiglio e valutazioni.
# Mancano "binding" e "hook": gli originali hanno una scritta pubblicitaria sopra le figure.
EXTRA = {
    "abyss": "L'Abisso",
    "accordion": "La Fisarmonica",
    "acrobat": "L'Acrobata",
    "adventurer": "L'Avventuriero",
    "air-rider": "Il Cavaliere dell'Aria",
    "airplane": "L'Aeroplano",
    "alley": "Il Vicolo",
    "amazing-meeting": "L'Incontro Straordinario",
    "american-pie": "La Torta Americana",
    "amphibian": "L'Anfibio",
    "anaconda": "L'Anaconda",
    "angry-pirate": "Il Pirata Furioso",
    "anna": "Anna",
    "ape": "La Scimmia",
    "apex": "Il Culmine",
    "aphrodite": "Afrodite",
    "apollo": "Apollo",
    "apologies": "Le Scuse",
    "appetite": "L'Appetito",
    "aquarius": "L'Acquario",
    "arch": "L'Arco",
    "aries": "L'Ariete",
    "asteroid": "L'Asteroide",
    "astrologer": "L'Astrologo",
    "avalanche": "La Valanga",
    "awesome-idea": "L'Idea Geniale",
    "back-door": "La Porta sul Retro",
    "backrest": "Lo Schienale",
    "backshot": "Il Colpo da Dietro",
    "backstroke": "Il Dorso",
    "backwards-cowgirl": "La Cowgirl al Contrario",
    "ball": "La Palla",
    "ballet-dancer": "La Ballerina",
    "banana-split": "La Banana Split",
    "barbell": "Il Bilanciere",
    "barberry": "Il Crespino",
    "barbie": "Barbie",
    "basket": "Il Cesto",
    "basset-hound": "Il Bassotto",
    "batman": "Batman",
    "belt": "La Cintura",
    "bench": "La Panchina",
    "bent-cowgirl": "La Cowgirl Piegata",
    "bermuda-triangle": "Il Triangolo delle Bermuda",
    "bicycle": "La Bicicletta",
    "birthday-party": "La Festa di Compleanno",
    "bizet": "Bizet",
    "blade": "La Lama",
    "boat": "La Barca",
    "bomb": "La Bomba",
    "book": "Il Libro",
    "bowstring": "La Corda dell'Arco",
    "brazilian-capoeira": "La Capoeira Brasiliana",
    "breeze": "La Brezza",
    "brute": "Il Bruto",
    "bulldog": "Il Bulldog",
    "bullfighter": "Il Torero",
    "bung": "Il Tappo",
    "butler": "Il Maggiordomo",
    "butter-churner": "La Zangola",
    "canadian": "La Canadese",
    "cancer": "Il Cancro",
    "capricorn": "Il Capricorno",
    "captain": "Il Capitano",
    "captivity": "La Prigionia",
    "car-mechanic": "Il Meccanico",
    "caramel": "Il Caramello",
    "case": "L'Astuccio",
    "casket": "Lo Scrigno",
    "cat": "La Gatta",
    "catch": "La Presa",
    "cave": "La Caverna",
    "cello": "Il Violoncello",
    "chairman": "Il Presidente",
    "chameleon": "Il Camaleonte",
    "chef": "Lo Chef",
    "chibi": "Il Chibi",
    "chili-dog": "L'Hot Dog Piccante",
    "chinese-art": "L'Arte Cinese",
    "circle": "Il Cerchio",
    "clapper": "Il Batacchio",
    "clip": "La Molletta",
    "clock": "L'Orologio",
    "close-breathing": "Respiro a Respiro",
    "coffee-table": "Il Tavolino",
    "column": "La Colonna",
    "comfortable-place": "Il Posto Comodo",
    "compliment": "Il Complimento",
    "concubine": "La Concubina",
    "conqueror": "Il Conquistatore",
    "contortionist": "La Contorsionista",
    "counterblow": "Il Contraccolpo",
    "courtesan": "La Cortigiana",
    "cowboy": "Il Cowboy",
    "cowgirl-on-the-table": "La Cowgirl sul Tavolo",
    "crab": "Il Granchio Rovesciato",
    "cradle": "La Culla",
    "crazy-doggy": "La Pecorina Pazza",
    "crazy-monkey": "La Scimmia Pazza",
    "crazy-train": "Il Treno Impazzito",
    "creme-brulee": "La Crème Brûlée",
    "croissant": "Il Croissant",
    "crouching-tiger": "La Tigre Accovacciata",
    "crucifixion": "La Croce",
    "curiosity": "La Curiosità",
    "deck-chair": "Il Lettino",
    "deep-stick": "Il Colpo Profondo",
    "deep-throat": "La Gola Profonda",
    "dejavu": "Il Déjà-vu",
    "delicacy": "La Prelibatezza",
    "depth": "La Profondità",
    "descent": "La Discesa",
    "desert-island": "L'Isola Deserta",
    "diamond": "Il Diamante",
    "dirty-dancing": "Dirty Dancing",
    "dirty-sanchez": "Lo Sporco Sanchez",
    "discharge": "La Scarica",
    "disco": "La Discoteca",
    "dive": "Il Tuffo",
    "doggy-on-the-edge": "La Pecorina sul Bordo",
    "doggy-on-the-edge-2": "La Pecorina sul Bordo II",
    "dolphin": "Il Delfino",
    "donkey-punch": "Il Calcio dell'Asino",
    "downstroke": "La Battuta",
    "dragon": "Il Drago",
    "dream": "Il Sogno",
    "drum": "Il Tamburo",
    "dutch-oven": "Il Forno Olandese",
    "eagle": "L'Aquila",
    "ebony": "L'Ebano",
    "ecstasy": "L'Estasi",
    "eiffel-tower": "La Torre Eiffel",
    "el-balancin": "Il Cavallo a Dondolo",
    "el-candelabro": "Il Candelabro",
    "el-columpio": "L'Altalena",
    "el-pretzel": "Il Pretzel",
    "el-sacacorchos": "Il Cavatappi",
    "el-tornillo": "La Vite",
    "el-ventilador": "Il Ventilatore",
    "elephant": "L'Elefante",
    "emmanuel": "Emmanuelle",
    "en-vilo": "Col Fiato Sospeso",
    "equilibrium": "L'Equilibrio",
    "eraser": "La Gomma",
    "erotic-poster": "Il Poster Erotico",
    "exciting-game": "Il Gioco Eccitante",
    "fairy": "La Fata",
    "fall": "La Caduta",
    "fallen-warrior": "Il Guerriero Caduto",
    "fantastic-elevator": "L'Ascensore Fantastico",
    "fantasy": "La Fantasia",
    "feeder": "La Mangiatoia",
    "female-peasant": "La Contadina",
    "fifth-element": "Il Quinto Elemento",
    "fire-hydrant": "L'Idrante",
    "fireman": "Il Pompiere",
    "fireworks": "I Fuochi d'Artificio",
    "flame": "La Fiamma",
    "flexible-beauty": "La Bella Flessuosa",
    "flying-dutchman": "L'Olandese Volante",
    "flying-squirrel": "Lo Scoiattolo Volante",
    "forbidden-fruit": "Il Frutto Proibito",
    "french-kiss": "Il Bacio alla Francese",
    "frog": "La Ranocchia",
    "froggy-style": "Il Salto della Rana",
    "fulcrum": "Il Fulcro",
    "full-nelson": "La Full Nelson",
    "funny-joke": "Lo Scherzo",
    "fusion": "La Fusione",
    "g-force": "La Forza G",
    "gemini": "I Gemelli",
    "ghetto": "Il Quartiere",
    "gimlet": "Il Succhiello",
    "giraffe": "La Giraffa",
    "goddess": "La Dea",
    "gorge": "La Gola",
    "grasshopper": "La Cavalletta",
    "guillotine": "La Ghigliottina",
    "hard-worker": "Lo Stacanovista",
    "harmony": "L'Armonia",
    "harp": "L'Arpa",
    "helicopter": "L'Elicottero",
    "hill": "La Collina",
    "holder": "Il Sostegno",
    "holiday": "La Vacanza",
    "honeymoon": "La Luna di Miele",
    "hood": "Il Cappuccio",
    "hostage": "L'Ostaggio",
    "hot-carl": "Il Bollente Carl",
    "hot-lunch": "Il Pranzo Caldo",
    "hottest-lover": "L'Amante Focoso",
    "houdini": "Houdini",
    "hucklebuck": "L'Hucklebuck",
    "hummingbird": "Il Colibrì",
    "hunger": "La Fame",
    "ice-cream": "Il Gelato",
    "idyll": "L'Idillio",
    "indian-style": "All'Indiana",
    "inquisitor": "L'Inquisitore",
    "insatiable-clitoris": "L'Insaziabile",
    "inseminator": "L'Inseminatore",
    "inventive-69": "Il 69 Fantasioso",
    "iris": "L'Iris",
    "iron": "Il Ferro",
    "iron-throne": "Il Trono di Spade",
    "italian-chandelier": "Il Lampadario Italiano",
    "jack": "Il Cric",
    "jackhammer": "Il Martello Pneumatico",
    "jamaican-cocktail": "Il Cocktail Giamaicano",
    "japan": "Il Giappone",
    "jellyfish": "La Medusa",
    "jockey": "Il Fantino",
    "joystick": "Il Joystick",
    "juego-previo": "I Preliminari",
    "juicy-ass": "La Pesca",
    "julia": "Giulia",
    "keeper": "Il Custode",
    "khaleesi": "Khaleesi",
    "kinky-spider": "Il Ragno Malizioso",
    "kitchen": "La Cucina",
    "knight": "Il Cavaliere",
    "knot": "Il Nodo",
    "la-amazona": "La Guerriera",
    "la-catapulta": "La Catapulta",
    "la-cobra": "Il Cobra",
    "la-montana-magica": "La Montagna Magica",
    "la-silla-de-la-reina": "La Sedia della Regina",
    "la-vaquera": "La Cowgirl",
    "lace": "Il Pizzo",
    "ladies-man": "Il Dongiovanni",
    "ladyboy": "La Lady",
    "las-tijeras": "La Sforbiciata",
    "launch-pad": "La Rampa di Lancio",
    "lazy-dog": "Il Cane Pigro",
    "lazy-evening": "La Serata Pigra",
    "leapfrog": "La Cavallina",
    "legs-in-the-air": "Gambe all'Aria",
    "legs-on-shoulders": "Gambe sulle Spalle",
    "leo": "Il Leone",
    "leopard": "Il Leopardo",
    "liana": "La Liana",
    "libido": "La Libido",
    "libra": "La Bilancia",
    "lizard": "La Lucertola",
    "lock": "Il Lucchetto",
    "london-bridge": "Il Ponte di Londra",
    "look-to-the-sky": "Lo Sguardo al Cielo",
    "loop": "L'Anello",
    "louise": "Luisa",
    "low-doggy": "La Pecorina Bassa",
    "low-start": "La Partenza dai Blocchi",
    "magic-carpet": "Il Tappeto Volante",
    "marsh-mallow": "Il Marshmallow",
    "master": "Il Maestro",
    "merger": "L'Unione",
    "mermaid": "La Sirena",
    "mexican-halloween": "L'Halloween Messicano",
    "mexican-style": "Alla Messicana",
    "midnight": "La Mezzanotte",
    "military-style": "Alla Militare",
    "milk-chocolate": "Il Cioccolato al Latte",
    "mirage": "Il Miraggio",
    "moan": "Il Gemito",
    "moonlight": "Il Chiaro di Luna",
    "mountain-creek": "Il Ruscello di Montagna",
    "multiply-pleasure": "Il Piacere Moltiplicato",
    "narcissus": "Il Narciso",
    "nasty-desire": "Il Desiderio Sfacciato",
    "necktie": "La Cravatta",
    "need-for-speed": "Voglia di Velocità",
    "new-69-on-the-chair": "Il 69 sulla Sedia",
    "niagara-falls": "Le Cascate del Niagara",
    "nice-talk": "La Bella Chiacchierata",
    "night-fly": "Il Volo Notturno",
    "nirvana": "Il Nirvana",
    "nosedive": "La Picchiata",
    "nun": "La Suora",
    "oasis": "L'Oasi",
    "octopus": "Il Polpo",
    "olympus": "L'Olimpo",
    "orchid": "L'Orchidea",
    "orgazm-generator": "Il Generatore di Orgasmi",
    "orgazmic-penetration": "L'Affondo Orgasmico",
    "overpass": "Il Cavalcavia",
    "overturned": "La Capovolta",
    "passive-doggy": "La Pecorina Passiva",
    "pearl": "La Perla",
    "penguin": "Il Pinguino",
    "pie-in-the-sky": "Il Castello in Aria",
    "pinwheel": "La Girandola",
    "pioneer": "Il Pioniere",
    "pisces": "I Pesci",
    "plaid": "Il Plaid",
    "plain": "La Pianura",
    "plank": "La Plancia",
    "playboy": "Il Playboy",
    "pleasure-bible": "La Bibbia del Piacere",
    "plow": "L'Aratro",
    "plumber": "L'Idraulico",
    "pointer": "La Lancetta",
    "pokemon": "Il Pokémon",
    "poplar": "Il Pioppo",
    "praying-mantis": "La Mantide Religiosa",
    "precipice": "Il Precipizio",
    "princess": "La Principessa",
    "prison-guard": "Il Secondino",
    "prone-bone": "A Pancia in Giù",
    "propeller": "L'Elica",
    "pterodactyl": "Lo Pterodattilo",
    "punishment": "La Punizione",
    "puzzle": "Il Puzzle",
    "python": "Il Pitone",
    "rabbit-ears": "Le Orecchie da Coniglio",
    "rainbow": "L'Arcobaleno",
    "rare-trick": "Il Numero Raro",
    "rear-admiral": "Il Contrammiraglio",
    "recharge": "La Ricarica",
    "reflection": "Il Riflesso",
    "relaxation": "Il Relax",
    "revelation": "La Rivelazione",
    "reverse-connection": "La Connessione Inversa",
    "reverse-cowboy": "Il Cowboy al Contrario",
    "reverse-doggy": "La Pecorina al Contrario",
    "ribbon-reverse-spoon": "Il Cucchiaio Rovesciato",
    "riverside": "La Riva del Fiume",
    "rocket": "Il Razzo",
    "rodeo": "Il Rodeo",
    "rose": "La Rosa",
    "russian-roulette": "La Roulette Russa",
    "saddle": "La Sella",
    "satyr": "Il Satiro",
    "scorpio": "Lo Scorpione",
    "scorpion": "La Coda dello Scorpione",
    "screwdriver": "Il Cacciavite",
    "sea-horse": "Il Cavalluccio Marino",
    "seashell": "La Conchiglia di Mare",
    "secret-entrance": "L'Ingresso Segreto",
    "seesaw": "Il Bilico",
    "sensual-touch": "Il Tocco Sensuale",
    "sex-slave": "La Schiava d'Amore",
    "sexo-oral-pene": "Il Sesso Orale",
    "shameless": "La Spudorata",
    "she-wolf": "La Lupa",
    "shell": "La Conchiglia",
    "shining": "Lo Splendore",
    "shocker": "La Scossa",
    "shy-girl": "La Timida",
    "side-saddle": "All'Amazzone",
    "silence": "Il Silenzio",
    "skewer": "Lo Spiedo",
    "sledge": "Lo Slittino",
    "sleeping-beauty": "La Bella Addormentata",
    "slide": "Lo Scivolo",
    "slope": "Il Pendio",
    "snack": "Lo Spuntino",
    "snail": "La Lumaca",
    "snake": "Il Serpente",
    "snake-charmer": "L'Incantatrice di Serpenti",
    "snow-angel": "L'Angelo di Neve",
    "soft-chair": "La Sedia Morbida",
    "soft-landing": "L'Atterraggio Morbido",
    "soldier": "Il Soldato",
    "source": "La Sorgente",
    "sower": "Il Seminatore",
    "spanish-guitar": "La Chitarra Spagnola",
    "spanish-sunset": "Il Tramonto Spagnolo",
    "spark": "La Scintilla",
    "speaker": "L'Altoparlante",
    "special-breakfast": "La Colazione Speciale",
    "special-fellatio": "La Fellatio Speciale",
    "sphinx": "La Sfinge Egizia",
    "spicy-dish": "Il Piatto Piccante",
    "spider": "Il Ragno",
    "spider-monkey": "La Scimmia Ragno",
    "spiderman": "L'Uomo Ragno",
    "splitting-bamboo": "Il Bambù Spezzato",
    "spork": "La Forchetta",
    "spread-eagle": "L'Aquila ad Ali Spiegate",
    "spring": "La Molla",
    "sprout": "Il Germoglio",
    "st-valentines-day": "San Valentino",
    "staff": "Il Bastone",
    "star-wars": "Guerre Stellari",
    "starfish": "La Stella Marina",
    "stick-figure": "L'Omino Stilizzato",
    "straddle": "A Cavalcioni",
    "straight-line": "La Linea Retta",
    "stuntman": "Lo Stuntman",
    "submissive": "La Sottomessa",
    "sucker-punch": "Il Colpo a Sorpresa",
    "superhero": "Il Supereroe",
    "superman": "Superman",
    "supernova": "La Supernova",
    "superwoman": "Superwoman",
    "surf-board": "La Tavola da Surf",
    "sweet-pussy": "Il Dolce Nettare",
    "sweet-sin": "Il Dolce Peccato",
    "swing": "Il Dondolio",
    "swing-2": "Il Dondolio II",
    "symphony": "La Sinfonia",
    "t-square": "La Squadra",
    "tamer": "Il Domatore",
    "tangle": "Il Groviglio",
    "tango": "Il Tango",
    "tantra": "Il Tantra",
    "tantric-cosmo": "Il Cosmo Tantrico",
    "tea-bag": "La Bustina di Tè",
    "tea-bag-2": "La Bustina di Tè II",
    "temptation": "La Tentazione",
    "thirst": "La Sete",
    "thors-hammer": "Il Martello di Thor",
    "throat-swab": "Fino in Gola",
    "tiara": "La Tiara",
    "tight-pussy": "Stretta Stretta",
    "tight-squeeze": "La Morsa",
    "tiramisu": "Il Tiramisù",
    "titanic": "Il Titanic",
    "titanic-2": "Il Titanic II",
    "torch": "La Torcia",
    "tornado": "Il Tornado",
    "train": "Il Treno",
    "triceratops": "Il Triceratopo",
    "truck": "Il Camion",
    "trunk": "Il Tronco",
    "tug-of-war": "Il Tiro alla Fune",
    "tugboat": "Il Rimorchiatore",
    "tulip": "Il Tulipano",
    "turtle": "La Tartaruga",
    "twerk-on-dick": "Il Twerk",
    "twins": "Le Gemelle",
    "unicorn": "L'Unicorno",
    "unique-styles": "Lo Stile Unico",
    "v-formation": "La Formazione a V",
    "valedictorian": "Il Primo della Classe",
    "venus": "Venere",
    "venus-flytrap": "La Pianta Carnivora",
    "victory": "La Vittoria",
    "virgo": "La Vergine",
    "vulgar-chair": "La Sedia Sfacciata",
    "watch": "La Guardia",
    "waterfall": "Il Salto d'Acqua",
    "watering-can": "L'Annaffiatoio",
    "wedge": "Il Cuneo",
    "weightlessness": "L'Assenza di Gravità",
    "weird-fantasy": "La Strana Fantasia",
    "wheelbarrow-2": "La Carriola II",
    "whisper": "Il Sussurro",
    "wild-pony": "Il Pony Selvaggio",
    "wild-yoga": "Lo Yoga Selvaggio",
    "workout": "L'Allenamento",
    "worship": "L'Adorazione",
    "woven-rose": "La Rosa Intrecciata",
    "wrestling": "La Lotta",
    "x-factor": "Il Fattore X",
    "xxx": "XXX",
    "yin-yang": "Yin e Yang",
    "young-stallion": "Il Giovane Stallone",
    "zeus": "Zeus",
    "zodiac": "Lo Zodiaco",
    "zombie": "Lo Zombie",
}


def sort_key(item):
    """Ordine alfabetico per nome, senza contare l'articolo."""
    return re.sub(r"^(il|lo|la|le|i|gli|l')\s*", "", item[1].lower())


POSITIONS += [dict(id=img.replace("-", "_"), name=name, img=img) for img, name in sorted(EXTRA.items(), key=sort_key)]

# --- Illustrazioni ---------------------------------------------------------------------------

SIZE = 640                   # lato del quadrato finale
MARGIN = 0.05                # bordo vuoto intorno al disegno
FURNITURE = (236, 226, 246)  # colore di sedie, letti e divani sul tema scuro
VIOLET_HUE = 262 / 360       # tinta di arrivo del blu
ERASE = {"concubine": (588, 474, 659, 506)}  # scritte pubblicitarie da cancellare dagli originali
_cache = {}


def recolor(rgb):
    """Da un pixel su fondo bianco a un pixel RGBA per il tema scuro."""
    r, g, b = rgb
    low = min(rgb)
    if low >= 249:
        return (0, 0, 0, 0)
    if max(rgb) - low < 28:
        # Grigi: le linee degli arredi. Più sono scure, più sono opache.
        return FURNITURE + (min(255, int((255 - low) * 1.9)),)
    # Il bordo delle figure è sfumato sul bianco: si separa il colore pieno dalla copertura.
    a = min(1.0, (255 - low) / 205)
    r, g, b = (max(0.0, 255 - (255 - c) / a) / 255 for c in rgb)
    h, s, v = colorsys.rgb_to_hsv(r, g, b)
    if 0.50 < h < 0.72:
        r, g, b = colorsys.hsv_to_rgb(VIOLET_HUE, s * 0.74, min(1.0, v * 1.06))
    return (round(r * 255), round(g * 255), round(b * 255), round(a * 255))


def illustration(name, target):
    from PIL import Image
    found = glob.glob(os.path.join(ASSETS, f"imgi_*_{name}.png"))
    assert len(found) == 1, f"illustrazione non trovata o ambigua: {name}"
    src = Image.open(found[0]).convert("RGB")
    if name in ERASE:
        src.paste((255, 255, 255), ERASE[name])
    out = Image.new("RGBA", src.size)
    out.putdata([_cache.get(p) or _cache.setdefault(p, recolor(p)) for p in src.getdata()])
    out = out.crop(out.getbbox())
    side = round(SIZE * (1 - 2 * MARGIN))
    out.thumbnail((side, side), Image.LANCZOS)
    square = Image.new("RGBA", (SIZE, SIZE))
    square.paste(out, ((SIZE - out.width) // 2, (SIZE - out.height) // 2))
    square.save(target, "WEBP", quality=88, method=6)


def illustrations():
    os.makedirs(DRAWABLES, exist_ok=True)
    wanted = {f"pos_{p['id']}.webp" for p in POSITIONS}
    for stale in set(os.listdir(DRAWABLES)) - wanted:
        if stale.startswith("pos_"):
            os.remove(os.path.join(DRAWABLES, stale))
    with Pool() as pool:
        pool.starmap(illustration, [(p["img"], os.path.join(DRAWABLES, f"pos_{p['id']}.webp")) for p in POSITIONS])


# --- Generazione Kotlin ----------------------------------------------------------------------

HEADER = '''package com.funcouple.app

// FILE GENERATO da tools/gen_positions.py: modifica lo script, non questo file.

/**
 * [image] è l'illustrazione della posizione: A è la figura rosa, B quella viola.
 * Le posizioni senza scheda hanno solo nome e illustrazione: testi vuoti e valutazioni a zero.
 */
data class Position(
    val id: String,
    val name: String,
    val image: Int,
    val tagline: String = "",
    val difficulty: Int = 0,
    val intimacy: Int = 0,
    val intensity: Int = 0,
    val description: String = "",
    val tip: String = "",
)

val difficultyNames = listOf("", "Facile", "Media", "Difficile")

val positions = listOf(
'''


def kotlin():
    out = HEADER
    for p in POSITIONS:
        if "desc" not in p:
            out += f'    Position("{p["id"]}", "{p["name"]}", R.drawable.pos_{p["id"]}),\n'
            continue
        out += "    Position(\n"
        out += f'        id = "{p["id"]}",\n        name = "{p["name"]}",\n        image = R.drawable.pos_{p["id"]},\n'
        out += f'        tagline = "{p["tag"]}",\n'
        out += f'        difficulty = {p["d"]},\n        intimacy = {p["i"]},\n        intensity = {p["x"]},\n'
        out += f'        description = "{p["desc"]}",\n        tip = "{p["tip"]}",\n'
        out += "    ),\n"
    return out + ")\n"


if __name__ == "__main__":
    assert len({p["id"] for p in POSITIONS}) == len(POSITIONS), "id duplicati"
    assert len({p["name"] for p in POSITIONS}) == len(POSITIONS), "nomi duplicati"
    if os.path.isdir(ASSETS):
        illustrations()
    else:
        print("assets-kamasutra/ non c'è: illustrazioni non rigenerate")
    with open(OUT, "w") as f:
        f.write(kotlin())
    print(len(POSITIONS), "posizioni")
